"""Supabase as the desk's home: four tables in the Creative Triage project.

`editor_jobs` mirrors the ClickUp Video Pipeline and adds what the worker
learned; `editor_assets` is a row per piece of footage with its transcript;
`editor_versions` is a row per cut with its check report; `editor_notes` is
timestamped feedback. Row security is on with no policies, so only the
service key reaches them.

Rules the writes follow, learned the hard way on the radar:
- PostgREST refuses a bulk upsert whose rows carry different keys (PGRST102),
  so rows are grouped by key set before they are sent;
- a sync never overwrites what the worker learned, and the worker never
  overwrites what the board says;
- every write is an upsert or a patch by primary key, so a retry is harmless.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Iterable, Optional

from . import http

JOB_COLUMNS = {
    "task_id", "name", "url", "status", "client", "clients", "client_task_id", "editor", "editors", "request_type",
    "brief", "script_task_id", "script", "footage_url", "raw_url", "edited_url", "website",
    "due_at", "opened_at", "state", "ready", "missing", "files", "seconds", "transcript_chars",
    "prepared_at", "attempts", "error", "asked_for", "asked_at", "asked_by", "synced_at", "updated_at",
}
# What a board sync is allowed to touch. Worker state is not in this set.
BOARD_COLUMNS = {
    "name", "url", "status", "client", "clients", "client_task_id", "editor", "editors", "request_type", "brief",
    "footage_url", "raw_url", "edited_url", "website", "due_at", "opened_at", "synced_at", "updated_at",
}
ASSET_COLUMNS = {
    "id", "task_id", "kind", "drive_id", "name", "mime", "bytes", "seconds", "width", "height", "fps",
    "has_audio", "preview_url", "still_path", "language", "transcript", "words", "scenes", "script_hits",
    "method", "error", "at", "updated_at",
}
VERSION_COLUMNS = {
    "id", "task_id", "n", "url", "drive_id", "name", "bytes", "seconds", "width", "height", "fps",
    "ratio", "loudness", "transcript", "checks", "passed", "waived", "by_email", "by_name", "at", "updated_at",
}
NOTE_COLUMNS = {"id", "task_id", "version", "at_sec", "text", "by_email", "by_name", "source", "done", "at"}
# Who may open the cockpit. `active` is generated by the database from
# via_portal and via_clickup, so it is never written from here.
PERSON_COLUMNS = {"email", "name", "role", "via_portal", "via_clickup", "clickup_seen_at"}
FOREPLAY_COLUMNS = {
    "id", "ad_id", "name", "brand_id", "board_id", "board_name", "video", "image", "thumbnail",
    "foreplay_url", "link_url", "headline", "description", "cta_title", "display_format",
    "publisher_platform", "niches", "languages", "market_target", "live", "started_running",
    "running_duration", "video_duration", "full_transcription", "timestamped_transcription",
    "emotional_drivers", "persona", "synced_at",
}
MEETING_COLUMNS = {
    "recording_id", "title", "started_at", "ended_at", "url", "share_url", "host",
    "invitees", "invitee_emails", "summary_md", "action_items", "language", "synced_at",
}
# The client card behind a job: the brand work, read once per company.
CLIENT_COLUMNS = {
    "task_id", "name", "url", "status", "aliases", "dos_donts", "brand_dna_url", "brand_dna",
    "brand_dna_rev", "offer_url", "offer", "offer_rev", "drive_url", "website", "instagram",
    "docs_read_at", "docs_error", "synced_at", "updated_at",
}

JSON_COLUMNS = ("clients", "editors", "aliases", "invitees", "invitee_emails", "action_items", "publisher_platform",
                "niches", "languages", "emotional_drivers", "missing", "words", "scenes", "script_hits", "method", "checks", "waived")


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _q(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


class SupabaseError(Exception):
    pass


class Supabase:
    def __init__(self, url: str, key: str, *, bucket: str = "editor-stills", timeout: float = 60):
        if not url or not key:
            raise SupabaseError("DESK_SUPABASE_URL and DESK_SUPABASE_KEY are required")
        self.url = url.rstrip("/")
        self.key = key
        self.bucket = bucket
        self.timeout = timeout

    # ---- plumbing --------------------------------------------------------
    def _headers(self, prefer: Optional[str] = None, extra: Optional[dict[str, str]] = None) -> dict[str, str]:
        h = {"apikey": self.key, "Authorization": f"Bearer {self.key}", "Accept": "application/json"}
        if prefer:
            h["Prefer"] = prefer
        if extra:
            h.update(extra)
        return h

    def rest(self, method: str, path: str, *, json_body: Any = None, prefer: Optional[str] = None, retries: int = 2) -> Any:
        headers = self._headers(prefer)
        data = None
        if json_body is not None:
            headers["Content-Type"] = "application/json"
            data = json.dumps(json_body, ensure_ascii=False).encode("utf-8")
        _, _, body = http.request(
            method, f"{self.url}/rest/v1/{path}", headers=headers, data=data,
            timeout=self.timeout, retries=retries, ok_statuses=(200, 201, 204),
        )
        if not body:
            return None
        try:
            return json.loads(body.decode("utf-8"))
        except (ValueError, UnicodeDecodeError):
            return body.decode("utf-8", "replace")

    def select(self, table: str, params: str) -> list[dict[str, Any]]:
        rows = self.rest("GET", f"{table}?{params}")
        return rows if isinstance(rows, list) else []

    def upsert(self, table: str, rows: list[dict[str, Any]], on_conflict: str) -> int:
        if not rows:
            return 0
        groups: dict[tuple[str, ...], list[dict[str, Any]]] = {}
        for row in rows:
            groups.setdefault(tuple(sorted(row.keys())), []).append(row)
        for group in groups.values():
            for i in range(0, len(group), 200):
                self.rest(
                    "POST", f"{table}?on_conflict={on_conflict}",
                    json_body=group[i : i + 200],
                    prefer="resolution=merge-duplicates,return=minimal",
                )
        return len(rows)

    def patch(self, table: str, where: str, body: dict[str, Any]) -> None:
        if not body:
            return
        self.rest("PATCH", f"{table}?{where}", json_body=body, prefer="return=minimal")

    def delete(self, table: str, where: str) -> None:
        self.rest("DELETE", f"{table}?{where}", prefer="return=minimal")

    def ping(self) -> bool:
        self.rest("GET", "editor_jobs?select=task_id&limit=1")
        return True

    @staticmethod
    def _row(d: dict[str, Any], allowed: set[str]) -> dict[str, Any]:
        row = {k: v for k, v in d.items() if k in allowed}
        for k in JSON_COLUMNS:
            if k in row and row[k] is None:
                row[k] = []
        return row

    # ---- jobs ------------------------------------------------------------
    def existing_jobs(self, task_ids: Iterable[str]) -> dict[str, dict[str, Any]]:
        ids = [t for t in dict.fromkeys(task_ids) if t]
        out: dict[str, dict[str, Any]] = {}
        for i in range(0, len(ids), 100):
            chunk = ids[i : i + 100]
            rows = self.select(
                "editor_jobs",
                f"select=task_id,state,ready,prepared_at,attempts,script_task_id,error&task_id=in.({','.join(_q(t) for t in chunk)})",
            )
            for r in rows:
                out[r["task_id"]] = r
        return out

    def store_jobs(self, rows: list[dict[str, Any]]) -> dict[str, int]:
        """Board rows in. A job already known keeps its worker state; a new one starts at `new`."""
        stamp = now_iso()
        have = self.existing_jobs([r.get("task_id", "") for r in rows])
        fresh: list[dict[str, Any]] = []
        known: list[dict[str, Any]] = []
        for r in rows:
            tid = r.get("task_id")
            if not tid:
                continue
            if tid in have:
                body = self._row(r, BOARD_COLUMNS)
                body["updated_at"] = stamp
                known.append({**body, "task_id": tid})
            else:
                body = self._row(r, JOB_COLUMNS)
                body.update({"state": "new", "ready": False, "attempts": 0, "updated_at": stamp})
                fresh.append(body)
        self.upsert("editor_jobs", fresh, "task_id")
        self.upsert("editor_jobs", known, "task_id")
        return {"new": len(fresh), "updated": len(known)}

    def job(self, task_id: str) -> Optional[dict[str, Any]]:
        rows = self.select("editor_jobs", f"select=*&task_id=eq.{http.quote(task_id)}&limit=1")
        return rows[0] if rows else None

    def jobs_to_prepare(self, limit: int) -> list[dict[str, Any]]:
        """Open jobs the worker has not finished, oldest first, tried fewer than four times."""
        rows = self.select(
            "editor_jobs",
            "select=*&state=in.(\"new\",\"stale\")&attempts=lt.4&order=opened_at.asc&limit=" + str(int(limit)),
        )
        return rows

    def retire_missing(self, on_board: Iterable[str], stamp: str) -> dict[str, Any]:
        """Mark jobs whose card is no longer on the board.

        A card deleted in ClickUp used to leave a job here forever: "jg
        design" sat in the cockpit as Blocked for a day after the card was
        deleted (found 2026-09-19). Rows are kept rather than deleted, because
        the transcripts and storyboards under them cost real money to make;
        they move to `gone` and drop out of every view.

        This refuses to run on a suspiciously small board. A half-failed
        ClickUp read returning three cards must not retire the other thirty.
        """
        have = {str(t) for t in on_board if t}
        stored = self.select("editor_jobs", "select=task_id,state&state=neq.gone&limit=1000")
        if not stored:
            return {"retired": 0}
        if len(have) < max(1, len(stored) // 2):
            return {"retired": 0, "refused": f"the board returned only {len(have)} cards for {len(stored)} jobs"}
        missing = [r["task_id"] for r in stored if r.get("task_id") not in have]
        for task_id in missing:
            self.patch(
                "editor_jobs",
                f"task_id=eq.{http.quote(task_id)}",
                {"state": "gone", "error": "the card is no longer on the board", "updated_at": stamp},
            )
        return {"retired": len(missing), "task_ids": missing}

    def mark_job(self, task_id: str, **fields: Any) -> None:
        fields["updated_at"] = now_iso()
        self.patch("editor_jobs", f"task_id=eq.{http.quote(task_id)}", fields)

    # ---- assets, versions, notes -----------------------------------------
    def store_assets(self, rows: list[dict[str, Any]]) -> int:
        stamp = now_iso()
        clean = []
        for r in rows:
            body = self._row(r, ASSET_COLUMNS)
            body.setdefault("at", stamp)
            body["updated_at"] = stamp
            clean.append(body)
        return self.upsert("editor_assets", clean, "id")

    def assets(self, task_id: str) -> list[dict[str, Any]]:
        return self.select("editor_assets", f"select=*&task_id=eq.{http.quote(task_id)}&order=at.asc")

    def store_version(self, row: dict[str, Any]) -> str:
        stamp = now_iso()
        body = self._row(row, VERSION_COLUMNS)
        body.setdefault("at", stamp)
        body["updated_at"] = stamp
        self.upsert("editor_versions", [body], "id")
        return str(body.get("id") or "")

    def versions(self, task_id: str) -> list[dict[str, Any]]:
        return self.select("editor_versions", f"select=*&task_id=eq.{http.quote(task_id)}&order=n.asc")

    def store_notes(self, rows: list[dict[str, Any]]) -> int:
        return self.upsert("editor_notes", [self._row(r, NOTE_COLUMNS) for r in rows], "id")

    def notes(self, task_id: str) -> list[dict[str, Any]]:
        return self.select("editor_notes", f"select=*&task_id=eq.{http.quote(task_id)}&order=at.asc")

    # ---- people ----------------------------------------------------------
    def seats_from_board(self, people: list[dict[str, str]], stamp: str) -> dict[str, int]:
        """Whoever is Assigned Editor on an open video card gets a seat.

        The desk writes `via_clickup` and nothing else. The portal writes
        `via_portal`; `active` is computed by the database from the two, so
        the two syncs cannot undo each other however they interleave.

        A seat is taken away the same way it was given: anyone this worker
        granted who is no longer on the board has their own flag cleared, and
        if the portal also granted them they keep their seat regardless.
        """
        want = {}
        for p in people:
            email = str(p.get("email") or "").strip().lower()
            if email:
                want[email] = str(p.get("name") or "")
        rows = [
            {"email": e, "via_clickup": True, "clickup_seen_at": stamp, **({"name": n} if n else {})}
            for e, n in want.items()
        ]
        added = self.upsert("editor_people", rows, "email") if rows else 0

        held = self.select("editor_people", "select=email&via_clickup=is.true")
        stale = [r["email"] for r in held if str(r.get("email") or "").lower() not in want]
        for email in stale:
            self.patch("editor_people", f"email=eq.{http.quote(email)}", {"via_clickup": False})
        return {"granted": added, "revoked": len(stale)}

    # ---- team meetings ---------------------------------------------------
    def store_meetings(self, rows: list[dict[str, Any]]) -> int:
        stamp = now_iso()
        clean = []
        for r in rows:
            body = {k: v for k, v in r.items() if k in MEETING_COLUMNS}
            if not body.get("recording_id"):
                continue
            body["synced_at"] = stamp
            clean.append(body)
        return self.upsert("team_meetings", clean, "recording_id")

    # ---- the swipe file --------------------------------------------------
    def known_ideation_keys(self, keys: Iterable[str]) -> list[str]:
        """Which of these the ideation board has already seen, in any state.
        A dismissed idea must not come back on the next sync."""
        wanted = [k for k in dict.fromkeys(keys) if k]
        out: list[str] = []
        for i in range(0, len(wanted), 100):
            chunk = wanted[i : i + 100]
            rows = self.select(
                "ideation_posts",
                f"select=key&key=in.({','.join(_q(k) for k in chunk)})",
            )
            out += [str(r.get("key")) for r in rows if r.get("key")]
        return out

    def known_foreplay_ids(self, limit: int = 5000) -> list[str]:
        """What we already hold, so a sync can stop rather than pay again."""
        rows = self.select("foreplay_ads", f"select=id&limit={int(limit)}")
        return [str(r.get("id")) for r in rows if r.get("id")]

    def board_state(self) -> dict[str, dict[str, Any]]:
        """What we already know about each board, so a sync can skip the
        ones it read recently rather than paying for them again."""
        rows = self.select("foreplay_boards", "select=id,name,ads,ads_synced_at&limit=500")
        return {str(r["id"]): r for r in rows if r.get("id")}

    def store_boards(self, boards: list[dict[str, Any]]) -> list[str]:
        """Record every board and return the names of the ones we had never
        seen, so a board somebody adds is noticed rather than ignored."""
        if not boards:
            return []
        stamp = now_iso()
        known = {
            str(r.get("id"))
            for r in self.select("foreplay_boards", "select=id&limit=500")
        }
        fresh = [b for b in boards if str(b.get("id")) not in known]
        rows = []
        for b in boards:
            if not b.get("id"):
                continue
            row = {
                "id": str(b["id"]), "name": b.get("name"),
                "feeds_ideation": bool(b.get("feeds_ideation")),
                "ads": int(b.get("ads") or 0),
                "last_seen_at": stamp,
            }
            # Only a board we actually read gets a fresh read time, or a
            # skipped board would look current and never be read again.
            if b.get("read"):
                row["ads_synced_at"] = stamp
            rows.append(row)
        self.upsert("foreplay_boards", rows, "id")
        return [str(b.get("name") or b.get("id")) for b in fresh]

    def store_foreplay(self, rows: list[dict[str, Any]]) -> int:
        stamp = now_iso()
        clean = []
        for r in rows:
            body = {k: v for k, v in r.items() if k in FOREPLAY_COLUMNS}
            if not body.get("id"):
                continue
            body["synced_at"] = stamp
            clean.append(body)
        return self.upsert("foreplay_ads", clean, "id")

    # ---- clients ---------------------------------------------------------
    def store_clients(self, rows: list[dict[str, Any]]) -> int:
        """The roster from Clients - Mahara. A company already known keeps the
        document text it has unless this row carries fresher text."""
        stamp = now_iso()
        clean = []
        for r in rows:
            body = self._row(r, CLIENT_COLUMNS)
            if not body.get("task_id"):
                continue
            body.setdefault("synced_at", stamp)
            body["updated_at"] = stamp
            clean.append(body)
        return self.upsert("editor_clients", clean, "task_id")

    def clients(self, task_ids: Optional[Iterable[str]] = None) -> list[dict[str, Any]]:
        if task_ids is None:
            return self.select("editor_clients", "select=*&order=name.asc&limit=400")
        ids = [t for t in dict.fromkeys(task_ids) if t]
        if not ids:
            return []
        out: list[dict[str, Any]] = []
        for i in range(0, len(ids), 100):
            chunk = ids[i : i + 100]
            out += self.select("editor_clients", f"select=*&task_id=in.({','.join(_q(t) for t in chunk)})")
        return out

    def client(self, task_id: str) -> Optional[dict[str, Any]]:
        rows = self.select("editor_clients", f"select=*&task_id=eq.{http.quote(task_id)}&limit=1")
        return rows[0] if rows else None

    # ---- our own copy of an ad -------------------------------------------
    def store_winner_file(self, row: dict[str, Any]) -> None:
        body = {k: v for k, v in row.items() if k in
                {"ad_id", "video_id", "file_path", "file_bytes", "file_error"}}
        if not body.get("ad_id"):
            return
        body["file_at"] = now_iso()
        self.upsert("winner_ads", [body], "ad_id")

    def upload_ad_video(self, ad_id: str, blob: bytes) -> str:
        path = f"{ad_id}.mp4"
        headers = self._headers(extra={"Content-Type": "video/mp4", "x-upsert": "true"})
        http.request(
            "POST", f"{self.url}/storage/v1/object/ad-videos/{http.quote(path)}",
            headers=headers, data=blob, timeout=300, retries=1, ok_statuses=(200, 201),
        )
        return path

    # ---- stills ----------------------------------------------------------
    def upload_still(self, task_id: str, name: str, blob: bytes, content_type: str = "image/jpeg") -> str:
        path = f"{task_id}/{name}"
        headers = self._headers(extra={"Content-Type": content_type, "x-upsert": "true"})
        http.request(
            "POST", f"{self.url}/storage/v1/object/{self.bucket}/{http.quote(path)}",
            headers=headers, data=blob, timeout=self.timeout, retries=1, ok_statuses=(200, 201),
        )
        return path
