import type { MetricDefinition, MetricValue, Unit } from "./metricRegistry";
import type { WebinarPayload, WebinarRound } from "./payloads";

type Entry = [
  string,
  string,
  Unit,
  string,
  string,
  (r: WebinarRound) => number | null,
];
const entries: Entry[] = [
  [
    "spend",
    "Webinar ad spend",
    "usd",
    "Meta snapshots",
    "Spend from webinar campaigns assigned to this round, including webinar retargeting.",
    r => r.traffic.spend,
  ],
  [
    "impressions",
    "Webinar impressions",
    "count",
    "Meta snapshots",
    "Impressions from this round's webinar ads.",
    r => r.traffic.impressions,
  ],
  [
    "reach",
    "Webinar reach",
    "count",
    "Meta insights",
    "Unique reach for the round's dates; never summed across days.",
    r => r.traffic.reach,
  ],
  [
    "frequency",
    "Webinar frequency",
    "ratio",
    "Meta insights",
    "Impressions per person reached for this round.",
    r => r.traffic.frequency,
  ],
  [
    "link_clicks",
    "Webinar link clicks",
    "count",
    "Meta snapshots",
    "Inline link clicks from this round's webinar ads.",
    r => r.traffic.linkClicks,
  ],
  [
    "registrations",
    "Webinar registrations",
    "count",
    "HighLevel",
    "Webby-tagged contacts assigned to their latest valid calendar-month round.",
    r => r.registration.registrations,
  ],
  [
    "cost_per_registration",
    "Cost per webinar registration",
    "usd",
    "Meta + HighLevel",
    "Round spend divided by registrations; null before any registration.",
    r => r.registration.costPerRegistration,
  ],
  [
    "qualified",
    "Qualified webinar registrants",
    "count",
    "HighLevel + Typeform",
    "Booking qualification wins, otherwise survey yearly net profit at least $100,000.",
    r => r.qualification.qualified,
  ],
  [
    "qualification_unknown",
    "Webinar qualification unknown",
    "count",
    "HighLevel + Typeform",
    "Registrants without a booking verdict or usable survey qualification.",
    r => r.qualification.unknown,
  ],
  [
    "cost_per_qualified",
    "Cost per qualified webinar registrant",
    "usd",
    "Meta + HighLevel + Typeform",
    "Round spend divided by qualified registrants.",
    r => r.qualification.costPerQualified,
  ],
  [
    "attended",
    "Webinar attendees",
    "count",
    "Zoom, otherwise HighLevel attendance tags",
    "Unique people in the room excluding the team; null until attendance is recorded.",
    r => (r.showUp.attendanceRecorded ? r.showUp.attended : null),
  ],
  [
    "show_rate",
    "Webinar show rate",
    "share",
    "Zoom + HighLevel",
    "Attendees divided by registrations using the cockpit's attendance evidence.",
    r => r.showUp.showRate,
  ],
  [
    "booked",
    "Webinar registrants who booked",
    "count",
    "HighLevel appointments",
    "Registrants with an intro or demo booked after their registration window begins.",
    r => r.conversion.booked,
  ],
  [
    "booked_while_live",
    "Webinar bookings while live",
    "count",
    "HighLevel appointments",
    "Registrants who booked between the real session start and three hours later.",
    r => r.conversion.bookedWhileLive,
  ],
  [
    "attendee_to_booked",
    "Webinar attendee to booked",
    "share",
    "Zoom + HighLevel",
    "Matched attendees who booked over attendees; unavailable without person-level identity evidence.",
    r => r.conversion.attendeeToBooked,
  ],
  [
    "registrant_to_booked",
    "Webinar registrant to booked",
    "share",
    "HighLevel",
    "Registrants who booked divided by registrations.",
    r => r.conversion.registrantToBooked,
  ],
  [
    "cost_per_booked",
    "Cost per webinar booking",
    "usd",
    "Meta + HighLevel",
    "Round spend divided by registrants who booked.",
    r => r.conversion.costPerBooked,
  ],
  [
    "calls_held",
    "Webinar registrants with held calls",
    "count",
    "HighLevel appointment statuses",
    "Registrants whose sales call meets the cockpit's shown-call rule.",
    r => r.sales.held,
  ],
  [
    "booked_to_held",
    "Webinar booked to held",
    "share",
    "HighLevel appointment statuses",
    "Held over due sales appointments using the displayed round's denominator.",
    r => r.sales.bookedToHeld,
  ],
  [
    "closes",
    "Webinar closes",
    "count",
    "Closer form",
    "Registrants with a signed deal after their registration window begins.",
    r => r.sales.closes,
  ],
  [
    "close_rate",
    "Webinar close rate",
    "share",
    "Closer form + HighLevel",
    "Closed registrants divided by held sales calls for this round.",
    r => r.sales.closeRate,
  ],
  [
    "contracted",
    "Webinar contracted revenue",
    "usd",
    "Closer form",
    "Contracted value of matched webinar deals; separate from cash.",
    r => r.sales.contracted,
  ],
  [
    "cash",
    "Webinar reported cash",
    "usd",
    "Closer form",
    "Cash reported on matched webinar deals; not all payment-verified.",
    r => r.sales.cash,
  ],
  [
    "cash_confirmed",
    "Webinar confirmed cash",
    "usd",
    "Closer form + payment evidence",
    "Cash on matched deals with a verified deposit, using the shared deposit rule.",
    r => r.sales.cashConfirmed,
  ],
  [
    "cac",
    "Webinar acquisition cost",
    "usd",
    "Meta + closer form",
    "Round ad spend divided by closes; excludes service delivery cost.",
    r => r.sales.cac,
  ],
  [
    "cash_roas",
    "Webinar cash ROAS",
    "ratio",
    "Meta + closer form",
    "Reported cash divided by round ad spend.",
    r => r.sales.roasCash,
  ],
  [
    "first_contact_minutes",
    "Webinar time to first contact",
    "minutes",
    "Maqsam + HighLevel",
    "Median minutes from the inferred registration start to the first sales-rep call.",
    r => r.sales.firstContactMedianMin,
  ],
];

export const WEBINAR_DEFINITIONS: MetricDefinition[] = entries.map(
  ([key, label, unit, source, definition]) => ({
    metric: `webinar.${key}`,
    section: "webinar",
    label,
    unit,
    source,
    definition,
    leavesOut:
      "Call-funnel traffic and pre-registration activity. Repeat registrants are attributed to the latest round; historical registrations are not reconstructed. Missing evidence remains null.",
  }),
);

/** Same payload as the screen, one scope per round; never mix rounds into company totals. */
export function extractWebinar(p: WebinarPayload): MetricValue[] {
  return p.rounds.flatMap(round =>
    entries.map(([key, , , , , read]) => {
      const n = read(round);
      return {
        metric: `webinar.${key}`,
        scope: `webinar:${round.key}`,
        window: "round",
        value: typeof n === "number" && Number.isFinite(n) ? n : null,
      };
    }),
  );
}
