import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const sql = name => readFileSync(new URL(`../../../supabase/migrations/${name}`,import.meta.url),'utf8');
const digest = 'a'.repeat(64), prefix = 'b'.repeat(64);
const upload = `/storage/v1/object/cockpit-ad-stills/${prefix}/${digest}`;
const publicUrl = `https://bldgtotkfmhoxmlzowdx.supabase.co/storage/v1/object/public/cockpit-ad-stills/${prefix}/${digest}`;
async function fixture(){
 const db=new PGlite();
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
 CREATE TABLE cockpit_sections(key text,ok boolean,error text,computed_at timestamptz);
 CREATE TABLE cockpit_media_provider_health(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,provider text,resource text,method text,phase text,http_status int,created_at timestamptz DEFAULT now());
 CREATE TABLE cockpit_ceo_provider_health(LIKE cockpit_media_provider_health INCLUDING ALL);
 CREATE TABLE cockpit_csm_provider_health(LIKE cockpit_media_provider_health INCLUDING ALL);
 CREATE TABLE cockpit_native_stills(key text PRIMARY KEY,data jsonb);
 CREATE TABLE cockpit_native_media_runs(run_id uuid PRIMARY KEY,status text,plan jsonb,created_at timestamptz DEFAULT now(),published_at timestamptz DEFAULT now());
 CREATE TABLE cockpit_ceo_refresh_runs(run_id uuid PRIMARY KEY,status text,created_at timestamptz,finished_at timestamptz);
 `);
 await db.exec(sql('20261004z_native_monitor.sql'));
 return db;
}
async function receipt(db,table,provider,resource,method,status,at,phase='response'){
 await db.query(`INSERT INTO ${table}(provider,resource,method,phase,http_status,created_at) VALUES($1,$2,$3,$4,$5,$6)`,[provider,resource,method,phase,status,at]);
}
async function open(db){const {rows}=await db.query("SELECT snapshot->'checks' AS checks FROM cockpit_native_monitor_state");return rows[0].checks.filter(c=>c.key.startsWith('source:cockpit_')&&!c.ok).map(c=>c.name).sort();}
async function publishedStill(db,url=publicUrl){await db.query("INSERT INTO cockpit_native_stills(key,data) VALUES('a:12345',$1)",[{key:'a:12345',status:'saved',url}]);await db.exec("INSERT INTO cockpit_native_media_runs(run_id,status,plan) VALUES('00000000-0000-0000-0000-000000000001','published','{}')");}
async function proof(db,resource=upload,hash=digest,at='2026-10-08T10:05:00Z',status=200){await db.query('INSERT INTO cockpit_native_still_readback(resource,sha256,http_status,verified_at) VALUES($1,$2,$3,$4)',[resource,hash,status,at]);}
async function setup(){const db=await fixture();await receipt(db,'cockpit_media_provider_health','storage',upload,'POST',400,'2026-10-08T10:00:00Z');return db;}
const migration='20261008j_native_receipt_classification.sql';
test('recovered storage POST 400 closes only with later hash readback and canonical published still',async()=>{const db=await setup();try{await publishedStill(db);await db.exec(sql(migration));assert.deepEqual(await open(db),['Provider storage']);await proof(db);assert.deepEqual(await open(db),[]);}finally{await db.close();}});
test('unverified, wrong hash, unpublished, stale, and absent still remain open',async()=>{for(const variant of ['wrong-hash','unpublished','stale','absent-still','wrong-url']){const db=await setup();try{if(variant!=='absent-still')await publishedStill(db,variant==='wrong-url'?publicUrl.replace(digest,'c'.repeat(64)):publicUrl);if(variant==='unpublished')await db.exec("UPDATE cockpit_native_media_runs SET status='failed'");await db.exec(sql(migration));if(variant==='wrong-hash')await assert.rejects(proof(db,upload,'c'.repeat(64)));else await proof(db,upload,digest,variant==='stale'?'2026-10-08T09:00:00Z':'2026-10-08T10:05:00Z');assert.deepEqual(await open(db),['Provider storage'],variant);}finally{await db.close();}}});
test('later CEO publish success supersedes identical method/resource failure, not unrelated failure',async()=>{const db=await fixture();try{const resource='bldgtotkfmhoxmlzowdx.supabase.co/rest/v1/rpc/cockpit_ceo_refresh_publish';await receipt(db,'cockpit_ceo_provider_health','supabase','other/endpoint','POST',400,'2026-10-08T10:00:00Z');await receipt(db,'cockpit_ceo_provider_health','supabase',resource,'POST',400,'2026-10-08T10:00:00Z');await receipt(db,'cockpit_ceo_provider_health','supabase',resource,'POST',200,'2026-10-08T10:05:00Z');await db.exec(sql(migration));assert.deepEqual(await open(db),['Provider supabase']);}finally{await db.close();}});
test('Sheets 403, Meta GET 400, unknown, and missing objects stay open; never blanket-filter 400',async()=>{const db=await setup();try{await receipt(db,'cockpit_csm_provider_health','google','sheets.googleapis.com/v4/spreadsheets/churn','GET',403,'2026-10-08T10:00:00Z');await receipt(db,'cockpit_media_provider_health','meta','graph.facebook.com/image','GET',400,'2026-10-08T10:00:00Z');await receipt(db,'cockpit_ceo_provider_health','supabase','other/unknown','POST',null,'2026-10-08T10:00:00Z','unknown');await db.exec(sql(migration));assert.deepEqual(await open(db),['Provider google','Provider meta','Provider storage','Provider supabase']);}finally{await db.close();}});
test('a newer failed upload reopens until its own later readback is verified',async()=>{const db=await setup();try{await publishedStill(db);await db.exec(sql(migration));await proof(db);await receipt(db,'cockpit_media_provider_health','storage',upload,'POST',400,'2026-10-08T10:10:00Z');assert.deepEqual(await open(db),['Provider storage']);await proof(db,upload,digest,'2026-10-08T10:15:00Z');assert.deepEqual(await open(db),[]);}finally{await db.close();}});
test('canonical later CEO publish closes historical publish error, not other endpoints',async()=>{const db=await fixture();try{const resource='bldgtotkfmhoxmlzowdx.supabase.co/rest/v1/rpc/cockpit_ceo_refresh_publish';await receipt(db,'cockpit_ceo_provider_health','supabase',resource,'POST',400,'2026-10-08T10:00:00Z');await receipt(db,'cockpit_ceo_provider_health','supabase','sheets.googleapis.com/churn','GET',403,'2026-10-08T10:00:00Z');await db.exec(sql(migration));assert.equal((await open(db)).length,2);await db.exec("INSERT INTO cockpit_ceo_refresh_runs VALUES('00000000-0000-0000-0000-000000000002','partial','2026-10-08T10:04:00Z','2026-10-08T10:05:00Z')");assert.deepEqual(await open(db),['Provider supabase']);}finally{await db.close();}});
test('batch of 39 verified stills closes while one unverified object remains open',async()=>{const db=await fixture();try{await db.exec("INSERT INTO cockpit_native_media_runs(run_id,status,plan) VALUES('00000000-0000-0000-0000-000000000001','published','{}')");for(let i=0;i<40;i++){const hash=i.toString(16).padStart(64,'0'),resource=`/storage/v1/object/cockpit-ad-stills/${prefix}/${hash}`;await receipt(db,'cockpit_media_provider_health','storage',resource,'POST',400,'2026-10-08T10:00:00Z');if(i<39)await db.query('INSERT INTO cockpit_native_stills(key,data) VALUES($1,$2)',[`a:${10000+i}`,{key:`a:${10000+i}`,status:'saved',url:`https://bldgtotkfmhoxmlzowdx.supabase.co/storage/v1/object/public/cockpit-ad-stills/${prefix}/${hash}`}]);}await db.exec(sql(migration));assert.equal((await open(db)).length,40);for(let i=0;i<39;i++){const hash=i.toString(16).padStart(64,'0');await proof(db,`/storage/v1/object/cockpit-ad-stills/${prefix}/${hash}`,hash);}assert.deepEqual(await open(db),['Provider storage']);}finally{await db.close();}});
test('migration reapplies without changing classification or granting browser access',async()=>{const db=await setup();try{await publishedStill(db);await db.exec(sql(migration));await proof(db);await db.exec(sql(migration));assert.deepEqual(await open(db),[]);const {rows}=await db.query("SELECT has_function_privilege('anon','public.cockpit_native_monitor()','EXECUTE') anon,has_table_privilege('authenticated','public.cockpit_native_still_readback','SELECT') reader");assert.deepEqual(rows,[{anon:false,reader:false}]);}finally{await db.close();}});
test('readback proof cannot claim failed GET or invalid digest',async()=>{const db=await setup();try{await db.exec(sql(migration));await assert.rejects(proof(db,upload,digest,'2026-10-08T10:05:00Z',404));await assert.rejects(proof(db,upload,'bad'));}finally{await db.close();}});
