-- Offline SQL integration fixture and test runner for 20260926a_cockpit_decision_details
-- Runs against a disposable PostgreSQL instance to verify contract without live DB calls.
-- Execute only through test-decision-details.cjs, in a disposable in-memory database.
\set ON_ERROR_STOP on
DO $$ BEGIN
  IF current_setting('cockpit.disposable_test', true) IS DISTINCT FROM 'on' THEN
    RAISE EXCEPTION 'Use the in-memory test-decision-details.cjs runner, never a live database';
  END IF;
END $$;

BEGIN;

-- 1. Mock Supabase auth schema and helpers
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE
);

-- Mock session state for testing different actors
CREATE TABLE IF NOT EXISTS public._test_session (
  current_uid uuid,
  current_roles text[]
);
TRUNCATE public._test_session;
INSERT INTO public._test_session (current_uid, current_roles) VALUES (NULL, ARRAY[]::text[]);

CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT current_uid FROM public._test_session LIMIT 1;
$$;

-- Mock role membership functions matching production pattern
CREATE OR REPLACE FUNCTION public.cockpit_has_role(p_role text) RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT coalesce(p_role = ANY(current_roles), false) FROM public._test_session LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.cockpit_is_ceo() RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT coalesce('ceo' = ANY(current_roles), false) FROM public._test_session LIMIT 1;
$$;

-- 2. Mock base table public.cockpit_decisions before migration
CREATE TABLE IF NOT EXISTS public.cockpit_decisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role text NOT NULL,
  day date NOT NULL,
  subject text NOT NULL,
  action text NOT NULL,
  kind text NOT NULL DEFAULT 'decision',
  evidence text,
  metric_at_decision numeric,
  logged_at timestamptz NOT NULL DEFAULT now(),
  source_system text NOT NULL DEFAULT 'supabase'
);

COMMIT;

-- 3. Apply the migration under test
\i supabase/migrations/20260926a_cockpit_decision_details.sql

-- 4. Execute test assertions
DO $$
DECLARE
  v_test_uid uuid := '11111111-1111-1111-1111-111111111111'::uuid;
  v_decision_id bigint;
  v_rec record;
  v_audit record;
  v_failed boolean;
BEGIN
  -- Setup test auth user
  INSERT INTO auth.users (id, email) VALUES (v_test_uid, 'fixture@tests.invalid')
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;

  --------------------------------------------------------------------------
  -- Test 1: Unauthenticated call rejection
  --------------------------------------------------------------------------
  UPDATE public._test_session SET current_uid = NULL, current_roles = ARRAY['media_buyer'];
  v_failed := false;
  BEGIN
    PERFORM public.cockpit_log_decision(
      'media_buyer',
      '2026-09-26'::date,
      'Test Campaign',
      'Raise budget',
      'decision',
      'Good performance',
      'Scale test',
      12.5,
      '{"amount": 100}'::jsonb
    );
  EXCEPTION WHEN SQLSTATE '42501' THEN
    v_failed := true;
  END;
  IF NOT v_failed THEN
    RAISE EXCEPTION 'Test 1 Failed: Unauthenticated caller was not rejected with 42501';
  END IF;

  --------------------------------------------------------------------------
  -- Test 2: Forbidden role rejection
  --------------------------------------------------------------------------
  UPDATE public._test_session SET current_uid = v_test_uid, current_roles = ARRAY['creative'];
  v_failed := false;
  BEGIN
    PERFORM public.cockpit_log_decision(
      'media_buyer',
      '2026-09-26'::date,
      'Test Campaign',
      'Raise budget'
    );
  EXCEPTION WHEN SQLSTATE '42501' THEN
    v_failed := true;
  END;
  IF NOT v_failed THEN
    RAISE EXCEPTION 'Test 2 Failed: Caller with wrong role was not rejected with 42501';
  END IF;

  --------------------------------------------------------------------------
  -- Test 3: Authorized call with reason, metadata, and metric = 0 persistence
  --------------------------------------------------------------------------
  UPDATE public._test_session SET current_uid = v_test_uid, current_roles = ARRAY['media_buyer'];

  v_decision_id := public.cockpit_log_decision(
    'media_buyer',
    '2026-09-26'::date,
    'Client Alpha',
    'Reroute lead form issue',
    'rerouted',
    'Form 404',
    'Tracking broke on new domain',
    0, -- Metric zero explicitly preserved
    '{"amount": 0, "reroutedTo": "tech"}'::jsonb
  );

  SELECT * INTO v_rec FROM public.cockpit_decisions WHERE id = v_decision_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Test 3 Failed: Decision row was not inserted';
  END IF;

  IF v_rec.reason IS DISTINCT FROM 'Tracking broke on new domain' THEN
    RAISE EXCEPTION 'Test 3 Failed: Reason not persisted (got %)', v_rec.reason;
  END IF;

  IF v_rec.metric_at_decision IS DISTINCT FROM 0 THEN
    RAISE EXCEPTION 'Test 3 Failed: Numeric metric 0 not persisted (got %)', v_rec.metric_at_decision;
  END IF;

  IF (v_rec.metadata->>'amount')::numeric IS DISTINCT FROM 0 THEN
    RAISE EXCEPTION 'Test 3 Failed: Metadata amount 0 not persisted (got %)', v_rec.metadata;
  END IF;

  IF v_rec.metadata->>'reroutedTo' IS DISTINCT FROM 'tech' THEN
    RAISE EXCEPTION 'Test 3 Failed: Metadata reroutedTo not persisted (got %)', v_rec.metadata;
  END IF;

  --------------------------------------------------------------------------
  -- Test 4: Audit trail verification on INSERT
  --------------------------------------------------------------------------
  SELECT * INTO v_audit FROM public.cockpit_audit_log
  WHERE entity_type = 'cockpit_decisions' AND entity_id = v_decision_id::text AND action = 'INSERT';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Test 4 Failed: Audit log INSERT row was not created';
  END IF;

  IF v_audit.actor_email IS DISTINCT FROM 'fixture@tests.invalid' THEN
    RAISE EXCEPTION 'Test 4 Failed: Audit actor incorrect (got %)', v_audit.actor_email;
  END IF;

  IF v_audit.before IS NOT NULL THEN
    RAISE EXCEPTION 'Test 4 Failed: Audit INSERT before should be NULL';
  END IF;

  IF v_audit.after->>'reason' IS DISTINCT FROM 'Tracking broke on new domain' THEN
    RAISE EXCEPTION 'Test 4 Failed: Audit INSERT after payload does not contain reason';
  END IF;

  --------------------------------------------------------------------------
  -- Test 5: Audit trail verification on UPDATE and DELETE
  --------------------------------------------------------------------------
  UPDATE public.cockpit_decisions
  SET reason = 'Updated reason'
  WHERE id = v_decision_id;

  SELECT * INTO v_audit FROM public.cockpit_audit_log
  WHERE entity_type = 'cockpit_decisions' AND entity_id = v_decision_id::text AND action = 'UPDATE';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Test 5 Failed: Audit log UPDATE row was not created';
  END IF;

  IF v_audit.before->>'reason' IS DISTINCT FROM 'Tracking broke on new domain'
     OR v_audit.after->>'reason' IS DISTINCT FROM 'Updated reason' THEN
    RAISE EXCEPTION 'Test 5 Failed: Audit UPDATE before/after mismatch';
  END IF;

  DELETE FROM public.cockpit_decisions WHERE id = v_decision_id;

  SELECT * INTO v_audit FROM public.cockpit_audit_log
  WHERE entity_type = 'cockpit_decisions' AND entity_id = v_decision_id::text AND action = 'DELETE';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Test 5 Failed: Audit log DELETE row was not created';
  END IF;

  IF v_audit.before->>'reason' IS DISTINCT FROM 'Updated reason' OR v_audit.after IS NOT NULL THEN
    RAISE EXCEPTION 'Test 5 Failed: Audit DELETE before/after mismatch';
  END IF;

  --------------------------------------------------------------------------
  -- Test 6: Audit log immutability check
  --------------------------------------------------------------------------
  v_failed := false;
  BEGIN
    DELETE FROM public.cockpit_audit_log WHERE entity_id = v_decision_id::text;
  EXCEPTION WHEN raise_exception THEN
    v_failed := true;
  END;
  IF NOT v_failed THEN
    RAISE EXCEPTION 'Test 6 Failed: Mutation on cockpit_audit_log was not prevented with 42501';
  END IF;

  RAISE NOTICE 'ALL 6 SQL INTEGRATION TESTS PASSED SUCCESSFULLY';
END;
$$;
