-- Phase 4: Cockpit Actions & RPCs Migration
-- Provides secure stored procedures for daily checks, EOD submissions, decisions,
-- client profile updates, plan items, and dashboard metrics.
-- Browser callers never write directly to domain tables; all writes are guarded by
-- strict role-verified SECURITY DEFINER functions with audit trails.

BEGIN;

-- 1. Cockpit Plan Items Table
CREATE TABLE IF NOT EXISTS public.cockpit_plan_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role text NOT NULL,
  day date NOT NULL,
  text text NOT NULL,
  reason text,
  client_name text,
  list_name text,
  due_date date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cockpit_plan_items_role_day
  ON public.cockpit_plan_items (role, day DESC);

ALTER TABLE public.cockpit_plan_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS plan_items_read_policy ON public.cockpit_plan_items;
CREATE POLICY plan_items_read_policy ON public.cockpit_plan_items
  FOR SELECT TO authenticated
  USING (
    public.cockpit_has_role(role)
    OR public.cockpit_has_role('admin')
    OR public.cockpit_is_ceo()
  );

REVOKE ALL ON TABLE public.cockpit_plan_items FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.cockpit_plan_items TO authenticated, service_role;
GRANT ALL ON TABLE public.cockpit_plan_items TO service_role;

-- 2. Ensure Unique Constraint on EOD Reports (role, day)
CREATE UNIQUE INDEX IF NOT EXISTS uq_cockpit_eod_role_day
  ON public.cockpit_eod_reports (role, day);

-- 3. RPC: Save End of Day (EOD) Report
CREATE OR REPLACE FUNCTION public.cockpit_save_eod(
  p_role text,
  p_day date,
  p_energy text DEFAULT NULL,
  p_answers jsonb DEFAULT '{}'::jsonb,
  p_computed jsonb DEFAULT '{}'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid;
  v_role text;
  v_id bigint;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sign in before saving EOD report' USING ERRCODE = '42501';
  END IF;

  v_role := trim(coalesce(p_role, ''));
  IF v_role NOT IN ('media_buyer', 'csm', 'creative', 'editor') OR p_day IS NULL THEN
    RAISE EXCEPTION 'Invalid EOD report role or day' USING ERRCODE = '22023';
  END IF;

  IF NOT (public.cockpit_has_role(v_role) OR public.cockpit_has_role('admin') OR public.cockpit_is_ceo()) THEN
    RAISE EXCEPTION 'Permission denied for EOD role: %', v_role USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.cockpit_eod_reports (
    role,
    day,
    submitted_at,
    energy,
    answers,
    computed,
    source_system,
    updated_at
  ) VALUES (
    v_role,
    p_day,
    now(),
    p_energy,
    coalesce(p_answers, '{}'::jsonb),
    coalesce(p_computed, '{}'::jsonb),
    'supabase',
    now()
  )
  ON CONFLICT (role, day) DO UPDATE
  SET energy = coalesce(EXCLUDED.energy, public.cockpit_eod_reports.energy),
      answers = EXCLUDED.answers,
      computed = EXCLUDED.computed,
      submitted_at = coalesce(public.cockpit_eod_reports.submitted_at, now()),
      source_system = 'supabase',
      updated_at = now()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- 4. RPC: Log Decision / Action
CREATE OR REPLACE FUNCTION public.cockpit_log_decision(
  p_role text,
  p_day date,
  p_subject text,
  p_action text,
  p_kind text DEFAULT 'decision',
  p_evidence text DEFAULT NULL,
  p_reason text DEFAULT NULL,
  p_metric_at_decision numeric DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid;
  v_role text;
  v_id bigint;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sign in before logging a decision' USING ERRCODE = '42501';
  END IF;

  v_role := trim(coalesce(p_role, ''));
  IF v_role NOT IN ('media_buyer', 'csm', 'creative', 'editor') OR p_day IS NULL THEN
    RAISE EXCEPTION 'Invalid decision role or day' USING ERRCODE = '22023';
  END IF;

  IF NOT (public.cockpit_has_role(v_role) OR public.cockpit_has_role('admin') OR public.cockpit_is_ceo()) THEN
    RAISE EXCEPTION 'Permission denied to log decision for role: %', v_role USING ERRCODE = '42501';
  END IF;

  IF trim(coalesce(p_subject, '')) = '' OR trim(coalesce(p_action, '')) = '' THEN
    RAISE EXCEPTION 'Subject and action cannot be empty' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.cockpit_decisions (
    role,
    day,
    subject,
    action,
    kind,
    evidence,
    metric_at_decision,
    logged_at,
    source_system
  ) VALUES (
    v_role,
    p_day,
    trim(p_subject),
    trim(p_action),
    coalesce(trim(p_kind), 'decision'),
    p_evidence,
    p_metric_at_decision,
    now(),
    'supabase'
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- 5. RPC: Remove Decision
CREATE OR REPLACE FUNCTION public.cockpit_remove_decision(
  p_id bigint
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid;
  v_role text;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sign in before removing a decision' USING ERRCODE = '42501';
  END IF;

  SELECT role INTO v_role
  FROM public.cockpit_decisions
  WHERE id = p_id;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF NOT (public.cockpit_has_role(v_role) OR public.cockpit_has_role('admin') OR public.cockpit_is_ceo()) THEN
    RAISE EXCEPTION 'Permission denied to remove decision' USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.cockpit_decisions WHERE id = p_id;
  RETURN true;
END;
$$;

-- 6. RPC: Update Client Profile
CREATE OR REPLACE FUNCTION public.cockpit_update_client_profile(
  p_client_name text,
  p_health text DEFAULT NULL,
  p_stage text DEFAULT NULL,
  p_service text DEFAULT NULL,
  p_notes jsonb DEFAULT NULL,
  p_kpi jsonb DEFAULT NULL,
  p_overview jsonb DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid;
  v_name text;
  v_id bigint;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sign in before updating a client profile' USING ERRCODE = '42501';
  END IF;

  IF NOT (
    public.cockpit_has_role('csm')
    OR public.cockpit_has_role('media_buyer')
    OR public.cockpit_has_role('admin')
    OR public.cockpit_is_ceo()
  ) THEN
    RAISE EXCEPTION 'Permission denied to update client profiles' USING ERRCODE = '42501';
  END IF;

  v_name := trim(coalesce(p_client_name, ''));
  IF v_name = '' THEN
    RAISE EXCEPTION 'client_name cannot be empty' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.cockpit_client_profiles (
    client_name,
    health,
    stage,
    service,
    notes,
    kpi,
    overview,
    source_system,
    updated_at
  ) VALUES (
    v_name,
    p_health,
    p_stage,
    p_service,
    coalesce(p_notes, '[]'::jsonb),
    coalesce(p_kpi, '{}'::jsonb),
    coalesce(p_overview, '{}'::jsonb),
    'supabase',
    now()
  )
  ON CONFLICT (client_name) DO UPDATE
  SET health = coalesce(EXCLUDED.health, public.cockpit_client_profiles.health),
      stage = coalesce(EXCLUDED.stage, public.cockpit_client_profiles.stage),
      service = coalesce(EXCLUDED.service, public.cockpit_client_profiles.service),
      notes = coalesce(EXCLUDED.notes, public.cockpit_client_profiles.notes),
      kpi = coalesce(EXCLUDED.kpi, public.cockpit_client_profiles.kpi),
      overview = coalesce(EXCLUDED.overview, public.cockpit_client_profiles.overview),
      source_system = 'supabase',
      updated_at = now()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- 7. RPC: Add Plan Item
CREATE OR REPLACE FUNCTION public.cockpit_add_plan_item(
  p_role text,
  p_day date,
  p_text text,
  p_reason text DEFAULT NULL,
  p_client_name text DEFAULT NULL,
  p_list_name text DEFAULT NULL,
  p_due_date date DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid;
  v_role text;
  v_id bigint;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sign in before adding a plan item' USING ERRCODE = '42501';
  END IF;

  v_role := trim(coalesce(p_role, ''));
  IF v_role NOT IN ('media_buyer', 'csm', 'creative', 'editor') OR p_day IS NULL THEN
    RAISE EXCEPTION 'Invalid plan item role or day' USING ERRCODE = '22023';
  END IF;

  IF NOT (public.cockpit_has_role(v_role) OR public.cockpit_has_role('admin') OR public.cockpit_is_ceo()) THEN
    RAISE EXCEPTION 'Permission denied for plan item role: %', v_role USING ERRCODE = '42501';
  END IF;

  IF trim(coalesce(p_text, '')) = '' THEN
    RAISE EXCEPTION 'Plan item text cannot be empty' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.cockpit_plan_items (
    role,
    day,
    text,
    reason,
    client_name,
    list_name,
    due_date,
    created_at
  ) VALUES (
    v_role,
    p_day,
    trim(p_text),
    p_reason,
    p_client_name,
    p_list_name,
    p_due_date,
    now()
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- 8. RPC: Remove Plan Item
CREATE OR REPLACE FUNCTION public.cockpit_remove_plan_item(
  p_id bigint
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid;
  v_role text;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sign in before removing a plan item' USING ERRCODE = '42501';
  END IF;

  SELECT role INTO v_role
  FROM public.cockpit_plan_items
  WHERE id = p_id;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF NOT (public.cockpit_has_role(v_role) OR public.cockpit_has_role('admin') OR public.cockpit_is_ceo()) THEN
    RAISE EXCEPTION 'Permission denied to remove plan item' USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.cockpit_plan_items WHERE id = p_id;
  RETURN true;
END;
$$;

-- 9. RPC: Get Dashboard Summary
CREATE OR REPLACE FUNCTION public.cockpit_get_dashboard_summary(
  p_role text,
  p_day date
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid;
  v_role text;
  v_summary jsonb;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sign in before fetching dashboard summary' USING ERRCODE = '42501';
  END IF;

  v_role := trim(coalesce(p_role, ''));
  IF v_role NOT IN ('media_buyer', 'csm', 'creative', 'editor') OR p_day IS NULL THEN
    RAISE EXCEPTION 'Invalid role or day' USING ERRCODE = '22023';
  END IF;

  IF NOT (public.cockpit_has_role(v_role) OR public.cockpit_has_role('admin') OR public.cockpit_is_ceo()) THEN
    RAISE EXCEPTION 'Permission denied for dashboard summary: %', v_role USING ERRCODE = '42501';
  END IF;

  SELECT jsonb_build_object(
    'role', v_role,
    'day', p_day,
    'campaigns_count', (SELECT count(*) FROM public.cockpit_campaigns),
    'ads_count', (SELECT count(*) FROM public.cockpit_ads),
    'checks_total', (
      SELECT count(*) FROM public.cockpit_daily_checks
      WHERE role = v_role AND day = p_day AND source_deleted = false
    ),
    'checks_done', (
      SELECT count(*) FROM public.cockpit_daily_checks
      WHERE role = v_role AND day = p_day AND done = true AND source_deleted = false
    ),
    'decisions_today', (
      SELECT count(*) FROM public.cockpit_decisions
      WHERE role = v_role AND day = p_day
    ),
    'eod_submitted', (
      SELECT coalesce(submitted_at IS NOT NULL, false)
      FROM public.cockpit_eod_reports
      WHERE role = v_role AND day = p_day
    ),
    'spend_7d', (SELECT coalesce(sum(spend_7d), 0) FROM public.cockpit_campaigns),
    'leads_7d', (SELECT coalesce(sum(leads_7d), 0) FROM public.cockpit_campaigns)
  ) INTO v_summary;

  RETURN v_summary;
END;
$$;

-- 10. Grant Execute Privileges to authenticated role
GRANT EXECUTE ON FUNCTION public.cockpit_save_eod(text, date, text, jsonb, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cockpit_log_decision(text, date, text, text, text, text, text, numeric, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cockpit_remove_decision(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cockpit_update_client_profile(text, text, text, text, jsonb, jsonb, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cockpit_add_plan_item(text, date, text, text, text, text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cockpit_remove_plan_item(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cockpit_get_dashboard_summary(text, date) TO authenticated;

COMMIT;
