-- What a month costs, line by line (Aziz, 2026-10-02: "a spreadsheet in the
-- money section for all software expenses... especially for software that is
-- per seat. If I add a seat, it can easily just change how much the software
-- expenses should be... labor, overhead and marketing").
--
-- One row per software tool, other overhead line or marketing line, edited on
-- the CEO cockpit's Costs page. A line costs seats × the price per seat (or the
-- price alone when it is not per seat), a twelfth of that when it bills yearly,
-- and a usage-based line carries its monthly estimate as its price. Payroll is
-- not here: it is the roster (cockpit_people) and each person's commission
-- rule, priced on a plan's projections.
--
-- Only the CEO cockpit's backend reads or writes it, with the service key, so
-- no seat policy and no grant beyond service_role. Every save leaves a row in
-- the cockpit's audit trail (ceoAudit).

begin;

create table if not exists public.cockpit_cost_lines (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('software', 'overhead', 'marketing')),
  name text not null check (length(trim(name)) > 0),
  category text,
  billing text not null default 'monthly' check (billing in ('monthly', 'yearly', 'usage')),
  seats numeric check (seats is null or seats >= 0),
  unit_price numeric not null default 0 check (unit_price >= 0),
  currency text not null default 'USD',
  paid_with text,
  match text,
  status text not null default 'active' check (status in ('active', 'paused', 'cancelled')),
  note text,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by text
);

comment on table public.cockpit_cost_lines is
  'What a month costs, line by line: software (often per seat), other overhead and marketing. Edited on the CEO cockpit''s Costs page.';
comment on column public.cockpit_cost_lines.seats is
  'Seats paid for, or null when the line is not priced per seat.';
comment on column public.cockpit_cost_lines.unit_price is
  'The price per seat (or the flat price) per billing period, in currency. A usage-based line carries its monthly estimate.';
comment on column public.cockpit_cost_lines.match is
  'How its charges read on a statement (a word in the merchant name), so the page can show the last charge.';

create index if not exists cockpit_cost_lines_kind on public.cockpit_cost_lines (kind, status, sort);

alter table public.cockpit_cost_lines enable row level security;
revoke all on public.cockpit_cost_lines from public, anon, authenticated;
grant all on public.cockpit_cost_lines to service_role;

notify pgrst, 'reload schema';

commit;
