-- Staff-owned CSM state is separate from refreshed client profile snapshots.
BEGIN;

CREATE OR REPLACE FUNCTION public.cockpit_client_allowed(p_name text)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF p_name IS NULL OR btrim(p_name)='' THEN RETURN false; END IF;
  IF public.cockpit_has_role('admin') OR public.cockpit_is_ceo() THEN RETURN true; END IF;
  RETURN EXISTS (
    SELECT 1 FROM public.cockpit_members m JOIN auth.users u ON u.id=m.auth_user_id
    WHERE m.auth_user_id=auth.uid() AND m.active AND u.email_confirmed_at IS NOT NULL
      AND m.email=lower(btrim(u.email))
      AND (cardinality(m.clients)=0 OR EXISTS (
        SELECT 1 FROM unnest(m.clients) n WHERE lower(btrim(n))=lower(btrim(p_name))
      ))
  );
END $$;

CREATE OR REPLACE FUNCTION public.cockpit_csm_actor()
RETURNS uuid LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF (public.cockpit_has_role('csm') OR public.cockpit_is_ceo()) IS NOT TRUE THEN
    RAISE EXCEPTION 'Active client-success access required' USING ERRCODE='42501';
  END IF;
  RETURN auth.uid();
END $$;

CREATE OR REPLACE FUNCTION public.cockpit_csm_hot_visible(p_name text,p_owner uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
  SELECT (p_name='' AND (p_owner=auth.uid() OR public.cockpit_is_ceo()))
    OR (p_name<>'' AND public.cockpit_client_allowed(p_name));
$$;
CREATE OR REPLACE FUNCTION public.cockpit_csm_month_valid(p_month text)
RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path='' AS $$
  SELECT coalesce(p_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$' AND left(p_month,4)<>'0000',false);
$$;
CREATE OR REPLACE FUNCTION public.cockpit_is_money_loose(p_text text)
RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path='' AS $$
  SELECT coalesce(p_text,'') ~* 'invoice|payment|past due|billing|pause|refund|card';
$$;

CREATE TABLE IF NOT EXISTS public.cockpit_csm_client_preferences (
  client_profile_id bigint PRIMARY KEY REFERENCES public.cockpit_client_profiles(id),
  language text NOT NULL CHECK(length(btrim(language)) BETWEEN 1 AND 30),
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  source_system text NOT NULL DEFAULT 'supabase', source_deployment text, source_id text
);
CREATE TABLE IF NOT EXISTS public.cockpit_csm_hot_rows (
  key text PRIMARY KEY CHECK(length(key) BETWEEN 1 AND 500),
  client_name text NOT NULL DEFAULT '' CHECK(length(client_name)<=500),
  owner_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  owner_email text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(data)='object'),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  source_system text NOT NULL DEFAULT 'supabase', source_deployment text, source_id text
);
CREATE TABLE IF NOT EXISTS public.cockpit_csm_loose_dismissals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_profile_id bigint NOT NULL REFERENCES public.cockpit_client_profiles(id),
  loose_text text NOT NULL,
  text_hash text GENERATED ALWAYS AS (md5(loose_text)) STORED,
  cleared_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  cleared_at timestamptz NOT NULL DEFAULT now(),
  source_system text NOT NULL DEFAULT 'supabase', source_deployment text, source_id text,
  UNIQUE(client_profile_id,text_hash)
);
CREATE TABLE IF NOT EXISTS public.cockpit_csm_money_goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  owner_email text NOT NULL,
  month text NOT NULL CHECK(public.cockpit_csm_month_valid(month)),
  target numeric CHECK(target IS NULL OR target>=0),
  clients integer CHECK(clients IS NULL OR clients>=0),
  counts jsonb NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(counts)='object'),
  updated_at timestamptz NOT NULL DEFAULT now(),
  source_system text NOT NULL DEFAULT 'supabase', source_deployment text, source_id text,
  UNIQUE(owner_id,month)
);

ALTER TABLE public.cockpit_csm_client_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cockpit_csm_hot_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cockpit_csm_loose_dismissals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cockpit_csm_money_goals ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.cockpit_csm_client_preferences,public.cockpit_csm_hot_rows,public.cockpit_csm_loose_dismissals,public.cockpit_csm_money_goals FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.cockpit_csm_client_preferences,public.cockpit_csm_hot_rows,public.cockpit_csm_loose_dismissals,public.cockpit_csm_money_goals TO authenticated;
GRANT ALL ON public.cockpit_csm_client_preferences,public.cockpit_csm_hot_rows,public.cockpit_csm_loose_dismissals,public.cockpit_csm_money_goals TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.cockpit_csm_loose_dismissals_id_seq,public.cockpit_csm_money_goals_id_seq TO service_role;
DROP POLICY IF EXISTS csm_preferences_read ON public.cockpit_csm_client_preferences;
CREATE POLICY csm_preferences_read ON public.cockpit_csm_client_preferences FOR SELECT TO authenticated
  USING ((public.cockpit_has_role('csm') OR public.cockpit_is_ceo()) AND EXISTS (
    SELECT 1 FROM public.cockpit_client_profiles p WHERE p.id=client_profile_id AND public.cockpit_client_allowed(p.client_name)));
DROP POLICY IF EXISTS csm_hot_read ON public.cockpit_csm_hot_rows;
CREATE POLICY csm_hot_read ON public.cockpit_csm_hot_rows FOR SELECT TO authenticated
  USING ((public.cockpit_has_role('csm') OR public.cockpit_is_ceo()) AND public.cockpit_csm_hot_visible(client_name,owner_id));
DROP POLICY IF EXISTS csm_dismissals_read ON public.cockpit_csm_loose_dismissals;
CREATE POLICY csm_dismissals_read ON public.cockpit_csm_loose_dismissals FOR SELECT TO authenticated
  USING ((public.cockpit_has_role('csm') OR public.cockpit_is_ceo()) AND EXISTS (
    SELECT 1 FROM public.cockpit_client_profiles p WHERE p.id=client_profile_id AND public.cockpit_client_allowed(p.client_name)));
DROP POLICY IF EXISTS csm_money_read ON public.cockpit_csm_money_goals;
CREATE POLICY csm_money_read ON public.cockpit_csm_money_goals FOR SELECT TO authenticated
  USING ((public.cockpit_has_role('csm') OR public.cockpit_is_ceo()) AND owner_id=auth.uid());

-- Keep the established admin/global and staff/client-list rules, consistently normalized.
ALTER TABLE public.cockpit_client_profiles ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.cockpit_client_profiles TO authenticated,service_role;
DROP POLICY IF EXISTS client_profiles_read_policy ON public.cockpit_client_profiles;
CREATE POLICY client_profiles_read_policy ON public.cockpit_client_profiles FOR SELECT TO authenticated
  USING ((public.cockpit_has_role('csm') OR public.cockpit_has_role('media_buyer') OR public.cockpit_is_ceo())
    AND public.cockpit_client_allowed(client_name));

CREATE OR REPLACE FUNCTION public.cockpit_csm_state(p_month text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
DECLARE uid uuid; day date:=(now() AT TIME ZONE 'Asia/Kuwait')::date; mon text;
  profiles jsonb; prefs jsonb; hot jsonb; dismissed jsonb; money jsonb;
BEGIN
  uid:=public.cockpit_csm_actor(); mon:=coalesce(p_month,to_char(day,'YYYY-MM'));
  IF NOT public.cockpit_csm_month_valid(mon) THEN RAISE EXCEPTION 'Invalid month' USING ERRCODE='22023'; END IF;
  SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.client_name),'[]') INTO profiles
    FROM public.cockpit_client_profiles p WHERE public.cockpit_client_allowed(p.client_name);
  SELECT coalesce(jsonb_agg(jsonb_build_object('clientName',p.client_name,'language',s.language) ORDER BY p.client_name),'[]') INTO prefs
    FROM public.cockpit_csm_client_preferences s JOIN public.cockpit_client_profiles p ON p.id=s.client_profile_id
    WHERE public.cockpit_client_allowed(p.client_name);
  SELECT coalesce(jsonb_agg(h.data || jsonb_build_object('key',h.key,'clientName',h.client_name,'at',extract(epoch FROM h.updated_at)*1000)
    ORDER BY h.created_at,h.key),'[]') INTO hot FROM public.cockpit_csm_hot_rows h
    WHERE public.cockpit_csm_hot_visible(h.client_name,h.owner_id);
  SELECT coalesce(jsonb_agg(jsonb_build_object('clientName',p.client_name,'text',d.loose_text)),'[]') INTO dismissed
    FROM public.cockpit_csm_loose_dismissals d JOIN public.cockpit_client_profiles p ON p.id=d.client_profile_id
    WHERE public.cockpit_client_allowed(p.client_name);
  SELECT jsonb_build_object('month',m.month,'target',m.target,'clients',m.clients,'counts',m.counts,
    'byEmail',m.owner_email,'at',extract(epoch FROM m.updated_at)*1000) INTO money
    FROM public.cockpit_csm_money_goals m WHERE m.owner_id=uid AND m.month=mon;
  RETURN jsonb_build_object('day',day::text,'month',mon,'profiles',profiles,'prefs',prefs,'hotRows',hot,'dismissed',dismissed,'money',money);
END $$;

CREATE OR REPLACE FUNCTION public.cockpit_csm_set_language(p_client_name text,p_language text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE uid uuid; profile_id bigint; canonical text;
BEGIN
  uid:=public.cockpit_csm_actor();
  IF public.cockpit_client_allowed(p_client_name) IS NOT TRUE THEN RAISE EXCEPTION 'Client access denied' USING ERRCODE='42501'; END IF;
  IF p_language IS NULL OR length(btrim(p_language)) NOT BETWEEN 1 AND 30 THEN RAISE EXCEPTION 'Invalid language' USING ERRCODE='22023'; END IF;
  SELECT id,client_name INTO profile_id,canonical FROM public.cockpit_client_profiles WHERE client_name=btrim(p_client_name);
  IF NOT FOUND THEN RAISE EXCEPTION 'Client is not in the roster' USING ERRCODE='22023'; END IF;
  INSERT INTO public.cockpit_csm_client_preferences(client_profile_id,language,updated_by)
    VALUES(profile_id,btrim(p_language),uid)
    ON CONFLICT(client_profile_id) DO UPDATE SET language=EXCLUDED.language,updated_by=uid,updated_at=now(),source_system='supabase';
  RETURN jsonb_build_object('clientName',canonical,'language',btrim(p_language));
END $$;

CREATE OR REPLACE FUNCTION public.cockpit_csm_save_hot_row(p_patch jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE uid uuid; email text; k text; v_key text; name text; old public.cockpit_csm_hot_rows;
  saved public.cockpit_csm_hot_rows; patch jsonb;
BEGIN
  uid:=public.cockpit_csm_actor();
  IF jsonb_typeof(p_patch) IS DISTINCT FROM 'object' OR jsonb_typeof(p_patch->'key') IS DISTINCT FROM 'string' THEN
    RAISE EXCEPTION 'A hot-list row needs a key' USING ERRCODE='22023';
  END IF;
  v_key:=p_patch->>'key';
  IF length(v_key) NOT BETWEEN 1 AND 500 THEN RAISE EXCEPTION 'Invalid row key' USING ERRCODE='22023'; END IF;
  FOR k IN SELECT jsonb_object_keys(p_patch) LOOP
    IF k<>ALL(ARRAY['key','clientName','type','leadType','status','lastObjection','contactUrl','amount','lastFu','nextFu','notes','manual','hidden']) THEN
      RAISE EXCEPTION 'Unknown hot-list field: %',k USING ERRCODE='22023';
    END IF;
    IF k IN ('manual','hidden') THEN
      IF jsonb_typeof(p_patch->k)<>'boolean' THEN RAISE EXCEPTION 'Invalid row flag' USING ERRCODE='22023'; END IF;
    ELSIF jsonb_typeof(p_patch->k)<>'string' AND NOT(k NOT IN ('key','clientName','type') AND p_patch->k='null'::jsonb) THEN
      RAISE EXCEPTION 'Hot-list values must be text' USING ERRCODE='22023';
    END IF;
  END LOOP;
  PERFORM pg_advisory_xact_lock(hashtextextended('csm-hot:' || v_key,0));
  SELECT * INTO old FROM public.cockpit_csm_hot_rows WHERE key=v_key FOR UPDATE;
  IF FOUND AND public.cockpit_csm_hot_visible(old.client_name,old.owner_id) IS NOT TRUE THEN
    RAISE EXCEPTION 'Hot-list row access denied' USING ERRCODE='42501';
  END IF;
  name:=btrim(coalesce(p_patch->>'clientName',old.client_name,''));
  IF length(name)>500 OR (name<>'' AND public.cockpit_client_allowed(name) IS NOT TRUE) THEN
    RAISE EXCEPTION 'Client access denied' USING ERRCODE='42501';
  END IF;
  SELECT lower(btrim(u.email)) INTO email FROM auth.users u WHERE u.id=uid;
  patch:=p_patch-'key'-'clientName';
  INSERT INTO public.cockpit_csm_hot_rows(key,client_name,owner_id,owner_email,data)
    VALUES(v_key,name,uid,email,jsonb_build_object('type','') || patch)
    ON CONFLICT(key) DO UPDATE SET client_name=name,data=public.cockpit_csm_hot_rows.data || patch,
      updated_at=now(),source_system='supabase'
    RETURNING * INTO saved;
  RETURN saved.data || jsonb_build_object('key',saved.key,'clientName',saved.client_name,'at',extract(epoch FROM saved.updated_at)*1000);
END $$;

CREATE OR REPLACE FUNCTION public.cockpit_csm_clear_loose(p_client_name text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE uid uuid; cleared integer; kept integer;
BEGIN
  uid:=public.cockpit_csm_actor();
  IF p_client_name IS NOT NULL AND public.cockpit_client_allowed(p_client_name) IS NOT TRUE THEN
    RAISE EXCEPTION 'Client access denied' USING ERRCODE='42501';
  END IF;
  SELECT count(*)::integer INTO kept FROM public.cockpit_client_profiles p
    CROSS JOIN LATERAL jsonb_array_elements(CASE WHEN jsonb_typeof(p.overview->'loose')='array' THEN p.overview->'loose' ELSE '[]'::jsonb END) item
    WHERE public.cockpit_client_allowed(p.client_name) AND (p_client_name IS NULL OR p.client_name=p_client_name)
      AND jsonb_typeof(item)='string' AND public.cockpit_is_money_loose(item#>>'{}');
  INSERT INTO public.cockpit_csm_loose_dismissals(client_profile_id,loose_text,cleared_by)
    SELECT p.id,item#>>'{}',uid FROM public.cockpit_client_profiles p
    CROSS JOIN LATERAL jsonb_array_elements(CASE WHEN jsonb_typeof(p.overview->'loose')='array' THEN p.overview->'loose' ELSE '[]'::jsonb END) item
    WHERE public.cockpit_client_allowed(p.client_name) AND (p_client_name IS NULL OR p.client_name=p_client_name)
      AND jsonb_typeof(item)='string' AND NOT public.cockpit_is_money_loose(item#>>'{}')
    ON CONFLICT(client_profile_id,text_hash) DO NOTHING;
  GET DIAGNOSTICS cleared=ROW_COUNT;
  RETURN jsonb_build_object('cleared',cleared,'kept',kept);
END $$;

CREATE OR REPLACE FUNCTION public.cockpit_csm_save_money_goals(p_patch jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE uid uuid; email text; mon text; k text; val jsonb; saved public.cockpit_csm_money_goals;
BEGIN
  uid:=public.cockpit_csm_actor();
  IF jsonb_typeof(p_patch) IS DISTINCT FROM 'object' OR jsonb_typeof(p_patch->'month') IS DISTINCT FROM 'string' THEN
    RAISE EXCEPTION 'Income plan needs a month' USING ERRCODE='22023';
  END IF;
  mon:=p_patch->>'month';
  IF NOT public.cockpit_csm_month_valid(mon) THEN RAISE EXCEPTION 'Invalid month' USING ERRCODE='22023'; END IF;
  FOR k IN SELECT jsonb_object_keys(p_patch) LOOP
    IF k<>ALL(ARRAY['month','target','clients','counts']) THEN RAISE EXCEPTION 'Unknown income-plan field' USING ERRCODE='22023'; END IF;
    IF k IN ('target','clients') AND p_patch->k<>'null'::jsonb THEN
      IF jsonb_typeof(p_patch->k)<>'number' OR (p_patch->>k)::numeric<0 THEN RAISE EXCEPTION 'Income values must be nonnegative numbers' USING ERRCODE='22023'; END IF;
      IF k='clients' AND (p_patch->>k)::numeric<>trunc((p_patch->>k)::numeric) THEN RAISE EXCEPTION 'Client count must be an integer' USING ERRCODE='22023'; END IF;
    END IF;
  END LOOP;
  IF p_patch ? 'counts' THEN
    IF jsonb_typeof(p_patch->'counts')<>'object' THEN RAISE EXCEPTION 'Counts must be an object' USING ERRCODE='22023'; END IF;
    FOR k,val IN SELECT key,value FROM jsonb_each(p_patch->'counts') LOOP
      IF jsonb_typeof(val)<>'number' OR val::text::numeric<0 THEN RAISE EXCEPTION 'Counts must be nonnegative numbers' USING ERRCODE='22023'; END IF;
    END LOOP;
  END IF;
  SELECT lower(btrim(u.email)) INTO email FROM auth.users u WHERE u.id=uid;
  INSERT INTO public.cockpit_csm_money_goals(owner_id,owner_email,month,target,clients,counts)
    VALUES(uid,email,mon,(p_patch->>'target')::numeric,(p_patch->>'clients')::integer,coalesce(p_patch->'counts','{}'))
    ON CONFLICT(owner_id,month) DO UPDATE SET
      target=CASE WHEN p_patch ? 'target' THEN EXCLUDED.target ELSE public.cockpit_csm_money_goals.target END,
      clients=CASE WHEN p_patch ? 'clients' THEN EXCLUDED.clients ELSE public.cockpit_csm_money_goals.clients END,
      counts=public.cockpit_csm_money_goals.counts || EXCLUDED.counts,updated_at=now(),source_system='supabase'
    RETURNING * INTO saved;
  RETURN jsonb_build_object('month',saved.month,'target',saved.target,'clients',saved.clients,'counts',saved.counts,
    'byEmail',saved.owner_email,'at',extract(epoch FROM saved.updated_at)*1000);
END $$;

-- A profile edit must not turn omitted notes/KPIs/overview into empty defaults.
CREATE OR REPLACE FUNCTION public.cockpit_merge_profile_fields(p_base jsonb,p_patch jsonb,p_depth integer DEFAULT 0)
RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SET search_path='' AS $$
DECLARE result jsonb; k text; v jsonb;
BEGIN
  IF p_depth>32 THEN RAISE EXCEPTION 'Profile fields are too deeply nested' USING ERRCODE='22023'; END IF;
  IF jsonb_typeof(p_patch) IS DISTINCT FROM 'object' THEN RETURN p_patch; END IF;
  IF p_patch='{}'::jsonb THEN RETURN coalesce(p_base,'{}'); END IF;
  result:=CASE WHEN jsonb_typeof(p_base)='object' THEN p_base ELSE '{}'::jsonb END;
  FOR k,v IN SELECT key,value FROM jsonb_each(p_patch) LOOP
    IF jsonb_typeof(v)='object' AND jsonb_typeof(result->k)='object' THEN
      v:=public.cockpit_merge_profile_fields(result->k,v,p_depth+1);
    END IF;
    result:=jsonb_set(result,ARRAY[k],v,true);
  END LOOP;
  RETURN result;
END $$;
CREATE OR REPLACE FUNCTION public.cockpit_update_client_profile(
  p_client_name text,p_health text DEFAULT NULL,p_stage text DEFAULT NULL,p_service text DEFAULT NULL,
  p_notes jsonb DEFAULT NULL,p_kpi jsonb DEFAULT NULL,p_overview jsonb DEFAULT NULL
)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE old public.cockpit_client_profiles;
BEGIN
  IF (public.cockpit_has_role('csm') OR public.cockpit_has_role('media_buyer') OR public.cockpit_is_ceo()) IS NOT TRUE
    OR public.cockpit_client_allowed(p_client_name) IS NOT TRUE THEN RAISE EXCEPTION 'Client access denied' USING ERRCODE='42501'; END IF;
  IF (p_kpi IS NOT NULL AND jsonb_typeof(p_kpi)<>'object') OR (p_overview IS NOT NULL AND jsonb_typeof(p_overview)<>'object') THEN
    RAISE EXCEPTION 'Profile fields must be objects' USING ERRCODE='22023';
  END IF;
  SELECT * INTO old FROM public.cockpit_client_profiles WHERE client_name=btrim(p_client_name) FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Client is not in the roster' USING ERRCODE='22023'; END IF;
  UPDATE public.cockpit_client_profiles SET health=coalesce(p_health,old.health),stage=coalesce(p_stage,old.stage),
    service=coalesce(p_service,old.service),notes=CASE WHEN p_notes IS NULL THEN old.notes ELSE public.cockpit_merge_profile_fields(old.notes,p_notes) END,
    kpi=CASE WHEN p_kpi IS NULL THEN old.kpi ELSE public.cockpit_merge_profile_fields(old.kpi,p_kpi) END,
    overview=CASE WHEN p_overview IS NULL THEN old.overview ELSE public.cockpit_merge_profile_fields(old.overview,p_overview) END,
    updated_at=now(),source_system='supabase' WHERE id=old.id;
  RETURN old.id;
END $$;

CREATE OR REPLACE FUNCTION public.cockpit_audit_csm_state()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE who text; row_data jsonb; entity text; name text;
BEGIN
  row_data:=CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  entity:=coalesce(row_data->>'id',row_data->>'key',row_data->>'client_profile_id');
  name:=row_data->>'client_name';
  IF row_data ? 'client_profile_id' THEN SELECT client_name INTO name FROM public.cockpit_client_profiles WHERE id=(row_data->>'client_profile_id')::bigint; END IF;
  SELECT lower(btrim(email)) INTO who FROM auth.users WHERE id=auth.uid();
  INSERT INTO public.cockpit_audit_log(action,entity_type,entity_id,actor_email,source_app,source_system,before,after,metadata)
    VALUES(TG_OP,TG_TABLE_NAME,entity,coalesce(who,session_user),'client-success','supabase',
      CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE NULL END,
      CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) ELSE NULL END,
      jsonb_build_object('client_name',name,'database_role',current_setting('role',true)));
  IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['cockpit_csm_client_preferences','cockpit_csm_hot_rows','cockpit_csm_loose_dismissals','cockpit_csm_money_goals','cockpit_client_profiles'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS csm_state_audit ON public.%I',t);
    EXECUTE format('CREATE TRIGGER csm_state_audit AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.cockpit_audit_csm_state()',t);
  END LOOP;
END $$;

REVOKE ALL ON FUNCTION public.cockpit_client_allowed(text),public.cockpit_csm_actor(),public.cockpit_csm_hot_visible(text,uuid),public.cockpit_csm_month_valid(text),public.cockpit_is_money_loose(text),public.cockpit_audit_csm_state() FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.cockpit_merge_profile_fields(jsonb,jsonb,integer) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.cockpit_client_allowed(text),public.cockpit_csm_hot_visible(text,uuid) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.cockpit_csm_month_valid(text) TO service_role;
REVOKE ALL ON FUNCTION public.cockpit_csm_state(text),public.cockpit_csm_set_language(text,text),public.cockpit_csm_save_hot_row(jsonb),public.cockpit_csm_clear_loose(text),public.cockpit_csm_save_money_goals(jsonb),public.cockpit_update_client_profile(text,text,text,text,jsonb,jsonb,jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.cockpit_csm_state(text),public.cockpit_csm_set_language(text,text),public.cockpit_csm_save_hot_row(jsonb),public.cockpit_csm_clear_loose(text),public.cockpit_csm_save_money_goals(jsonb),public.cockpit_update_client_profile(text,text,text,text,jsonb,jsonb,jsonb) TO authenticated,service_role;
COMMIT;
