BEGIN;

-- Allow client-scoped hot list opportunities to have genuinely unknown legacy author.
ALTER TABLE public.cockpit_csm_hot_rows ALTER COLUMN owner_email DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS cockpit_csm_hot_rows_source_identity ON public.cockpit_csm_hot_rows(source_deployment,source_id) WHERE source_id IS NOT NULL;

-- Source identity and indexing for imported CSM human state.
CREATE UNIQUE INDEX IF NOT EXISTS cockpit_csm_client_preferences_source_identity ON public.cockpit_csm_client_preferences(source_deployment,source_id) WHERE source_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS cockpit_csm_loose_dismissals_source_identity ON public.cockpit_csm_loose_dismissals(source_deployment,source_id) WHERE source_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS cockpit_csm_money_goals_email_month ON public.cockpit_csm_money_goals(lower(btrim(owner_email)),month);
CREATE UNIQUE INDEX IF NOT EXISTS cockpit_csm_money_goals_source_identity ON public.cockpit_csm_money_goals(source_deployment,source_id) WHERE source_id IS NOT NULL;
-- Full original records are provenance, not a replacement for the canonical domain fields.
DO $$ DECLARE target text; BEGIN
 FOREACH target IN ARRAY ARRAY['cockpit_csm_client_preferences','cockpit_csm_hot_rows','cockpit_csm_loose_dismissals','cockpit_csm_money_goals','cockpit_csm_projections','cockpit_csm_renewal_plans'] LOOP
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_record jsonb',target);
 END LOOP;
END $$;
ALTER TABLE public.cockpit_csm_projections ADD COLUMN IF NOT EXISTS source_deployment text;
ALTER TABLE public.cockpit_csm_renewal_plans ADD COLUMN IF NOT EXISTS source_deployment text;
CREATE UNIQUE INDEX cockpit_csm_projections_source_identity ON public.cockpit_csm_projections(source_deployment,source_id) WHERE source_id IS NOT NULL;
CREATE UNIQUE INDEX cockpit_csm_renewal_plans_source_identity ON public.cockpit_csm_renewal_plans(source_deployment,source_id) WHERE source_id IS NOT NULL;
-- This resolves recorded historical identity, not permission to act today.
CREATE FUNCTION public.cockpit_csm_history_owner(p_email text) RETURNS uuid
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
DECLARE matched bigint; resolved uuid;
BEGIN
 IF nullif(btrim(p_email),'') IS NULL THEN RETURN NULL;END IF;
 SELECT count(*),max(u.id::text)::uuid INTO matched,resolved
 FROM auth.users u JOIN public.cockpit_members m ON m.auth_user_id=u.id
 WHERE u.email_confirmed_at IS NOT NULL AND m.email=lower(btrim(u.email))
  AND lower(btrim(u.email))=lower(btrim(p_email));
 IF matched<>1 THEN RETURN NULL;END IF;
 RETURN resolved;
END $$;
REVOKE ALL ON FUNCTION public.cockpit_csm_history_owner(text) FROM PUBLIC,anon,authenticated,service_role;

-- Dedicated typed brief domain for original call briefs from Media Buyer.
-- Client language is genuinely optional in the source; do not require non-null language.
ALTER TABLE public.cockpit_csm_client_preferences ALTER COLUMN language DROP NOT NULL;
ALTER TABLE public.cockpit_csm_client_preferences DROP CONSTRAINT IF EXISTS cockpit_csm_client_preferences_language_check;
ALTER TABLE public.cockpit_csm_client_preferences ADD CONSTRAINT cockpit_csm_client_preferences_language_check CHECK(language IS NULL OR length(btrim(language)) BETWEEN 1 AND 30);

CREATE TABLE IF NOT EXISTS public.cockpit_media_call_briefs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name text NOT NULL,
  key text NOT NULL,
  job_id text,
  status text NOT NULL CHECK(status IN ('queued','done','failed')),
  overall text,
  per_call jsonb NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(per_call)='array'),
  at timestamptz NOT NULL DEFAULT now(),
  source_deployment text,
  source_id text,
  source_record jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(client_name,key)
);
CREATE UNIQUE INDEX IF NOT EXISTS cockpit_media_call_briefs_source_identity ON public.cockpit_media_call_briefs(source_deployment,source_id) WHERE source_id IS NOT NULL;

ALTER TABLE public.cockpit_media_call_briefs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.cockpit_media_call_briefs FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.cockpit_media_call_briefs TO authenticated;
GRANT SELECT,INSERT,UPDATE ON public.cockpit_media_call_briefs TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.cockpit_media_call_briefs_id_seq TO service_role;

DROP POLICY IF EXISTS csm_call_briefs_read ON public.cockpit_media_call_briefs;
CREATE POLICY csm_call_briefs_read ON public.cockpit_media_call_briefs FOR SELECT TO authenticated
  USING ((public.cockpit_has_role('csm') OR public.cockpit_has_role('media_buyer') OR public.cockpit_is_ceo())
    AND public.cockpit_client_allowed(client_name));

CREATE TRIGGER cockpit_call_briefs_audit AFTER INSERT OR UPDATE ON public.cockpit_media_call_briefs FOR EACH ROW EXECUTE FUNCTION public.cockpit_audit_csm_state();

CREATE OR REPLACE FUNCTION public.cockpit_csm_call_briefs(p_client_name text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF NOT(public.cockpit_has_role('csm') OR public.cockpit_has_role('media_buyer') OR public.cockpit_is_ceo()) THEN
    RAISE EXCEPTION 'Current confirmed cockpit access required' USING ERRCODE='42501';
  END IF;
  IF p_client_name IS NOT NULL AND public.cockpit_client_allowed(p_client_name) IS NOT TRUE THEN
    RAISE EXCEPTION 'Client access denied' USING ERRCODE='42501';
  END IF;
  RETURN coalesce((
    SELECT jsonb_agg(jsonb_build_object(
      '_id', coalesce(source_id, id::text),
      'clientName', client_name,
      'key', key,
      'jobId', job_id,
      'status', status,
      'overall', overall,
      'perCall', per_call,
      'at', extract(epoch FROM at) * 1000
    ) ORDER BY at DESC, id DESC)
    FROM public.cockpit_media_call_briefs
    WHERE (public.cockpit_has_role('csm') OR public.cockpit_has_role('media_buyer') OR public.cockpit_is_ceo())
      AND public.cockpit_client_allowed(client_name)
      AND (p_client_name IS NULL OR lower(btrim(client_name)) = lower(btrim(p_client_name)))
  ), '[]'::jsonb);
END $$;
REVOKE ALL ON FUNCTION public.cockpit_csm_call_briefs(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.cockpit_csm_call_briefs(text) TO authenticated;

COMMIT;
