-- Forward record of the verified UTC comparison fix. Business timestamps remain unchanged.
BEGIN;
CREATE OR REPLACE FUNCTION public.cockpit_native_durable_projection(p_table text,p_data jsonb) RETURNS jsonb
LANGUAGE sql IMMUTABLE SET search_path='' AS $$
 SELECT CASE p_table
  WHEN 'members' THEN jsonb_build_object('email',p_data->'email','name',p_data->'name','roles',p_data->'roles','clients',p_data->'clients','active',p_data->'active','sales_role',p_data->'sales_role','note',p_data->'note','added_by',p_data->'added_by','added_at',p_data->'added_at','source_updated_at',p_data->'source_updated_at','last_seen_at',p_data->'last_seen_at','last_cockpit',p_data->'last_cockpit','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  WHEN 'eodReports' THEN jsonb_build_object('role',p_data->'role','day',p_data->'day','submitted_at',p_data->'submitted_at','energy',p_data->'energy','answers',p_data->'answers','computed',p_data->'computed','slack_ts',p_data->'slack_ts','source_system',p_data->'source_system','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id','source_row',p_data->'source_row')
  WHEN 'checks' THEN jsonb_build_object('role',p_data->'role','owner_app',p_data->'owner_app','day',p_data->'day','check_key',p_data->'check_key','label',p_data->'label','detail',p_data->'detail','phase',p_data->'phase','block',p_data->'block','display_order',p_data->'display_order','href',p_data->'href','source_system',p_data->'source_system','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id','source_created_at',p_data->'source_created_at','source_row',p_data->'source_row')
  WHEN 'decisions' THEN jsonb_build_object('role',p_data->'role','day',p_data->'day','subject',p_data->'subject','action',p_data->'action','evidence',p_data->'evidence','kind',p_data->'kind','clickup_task_id',p_data->'clickup_task_id','clickup_task_url',p_data->'clickup_task_url','metric_at_decision',p_data->'metric_at_decision','logged_at',p_data->'logged_at','source_system',p_data->'source_system','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id','source_row',p_data->'source_row')
  WHEN 'feedback' THEN jsonb_build_object('kind',p_data->'kind','text',p_data->'text','created_by',p_data->'created_by','source_system',p_data->'source_system','source_id',p_data->'source_id','app',p_data->'app','page',p_data->'page','role',p_data->'role','actor_email',p_data->'actor_email','metadata',p_data->'metadata')
  WHEN 'ceoTeamStatus' THEN jsonb_build_object('person_key',p_data->'person_key','status',p_data->'status','since',p_data->'since','note',p_data->'note','set_by',p_data->'set_by','set_at',to_char((p_data->>'set_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'source_deployment',p_data->'source_deployment','source_id',p_data->'source_id','source_record',p_data->'source_record')
  WHEN 'planItems' THEN jsonb_build_object('role',p_data->'role','day',p_data->'day','text',p_data->'text','reason',p_data->'reason','client_name',p_data->'client_name','list_name',p_data->'list_name','due_date',p_data->'due_date','created_at',to_char((p_data->>'created_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'confirmed',p_data->'confirmed','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id','source_row',p_data->'source_row')
  WHEN 'ceoDaily' THEN jsonb_build_object('day',p_data->'day','metric',p_data->'metric','scope',p_data->'scope','value',to_jsonb((p_data->>'value')::double precision),'captured_at',to_char((p_data->>'captured_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'source_deployment',p_data->'source_deployment','source_id',p_data->'source_id','source_record',p_data->'source_record')
  WHEN 'ceoAudit' THEN jsonb_build_object('action',p_data->'action','entity_type',p_data->'entity_type','entity_id',p_data->'entity_id','actor_email',p_data->'actor_email','source_app',p_data->'source_app','source_system',p_data->'source_system','before',p_data->'before','after',p_data->'after','created_at',to_char((p_data->>'created_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'metadata',p_data->'metadata')
  WHEN 'ceoClientBilling' THEN to_jsonb(jsonb_populate_record(NULL::public.cockpit_client_billing_days,p_data)) ||
   jsonb_build_object('mrr_usd',to_jsonb((p_data->>'mrr_usd')::double precision),'ltv_usd',to_jsonb((p_data->>'ltv_usd')::double precision),'next_payment_usd',to_jsonb((p_data->>'next_payment_usd')::double precision),'captured_at',to_char((p_data->>'captured_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))
  WHEN 'clientPrefs' THEN jsonb_build_object('client_name',p_data->'client_name','language',p_data->'language','updated_by',p_data->'updated_by','source_system',p_data->'source_system','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  WHEN 'hotList' THEN jsonb_build_object('key',p_data->'key','client_name',p_data->'client_name','owner_email',p_data->'owner_email','data',p_data->'data','source_system',p_data->'source_system','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  WHEN 'looseDismissed' THEN jsonb_build_object('client_name',p_data->'client_name','loose_text',p_data->'loose_text','cleared_by',p_data->'cleared_by','cleared_at',to_char((p_data->>'cleared_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'source_system',p_data->'source_system','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  WHEN 'moneyGoals' THEN jsonb_build_object('owner_email',p_data->'owner_email','month',p_data->'month','target',to_jsonb((p_data->>'target')::double precision),'clients',to_jsonb((p_data->>'clients')::integer),'counts',p_data->'counts','source_system',p_data->'source_system','source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  WHEN 'projections' THEN jsonb_build_object('week_start',p_data->'week_start','owner_email',p_data->'owner_email','metric',p_data->'metric','data',p_data->'data','source_id',p_data->'source_id')
  WHEN 'renewalPlans' THEN jsonb_build_object('task_id',p_data->'task_id','client_name',p_data->'client_name','renewal_date',p_data->'renewal_date','data',p_data->'data','source_id',p_data->'source_id')
  WHEN 'callBriefs' THEN jsonb_build_object('client_name',p_data->'client_name','key',p_data->'key','job_id',p_data->'job_id','status',p_data->'status','overall',p_data->'overall','per_call',p_data->'per_call','at',to_char((p_data->>'at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  WHEN 'waThreads' THEN jsonb_build_object('source_app',p_data->'source_app','chat_id',p_data->'chat_id','channel',p_data->'channel','name',p_data->'name','client_name',p_data->'client_name','contact_id',p_data->'contact_id','source',p_data->'source','is_group',p_data->'is_group','unread',p_data->'unread','last_from_us',p_data->'last_from_us','silent_days',p_data->'silent_days','draft',p_data->'draft','recent',p_data->'recent','draft_at',CASE WHEN p_data->>'draft_at' IS NOT NULL THEN to_char((p_data->>'draft_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END,'last_at',to_char((p_data->>'last_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'waiting_since',CASE WHEN p_data->>'waiting_since' IS NOT NULL THEN to_char((p_data->>'waiting_since')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END,'synced_at',CASE WHEN p_data->>'synced_at' IS NOT NULL THEN to_char((p_data->>'synced_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END,'creation_time',to_char((p_data->>'creation_time')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  WHEN 'replyDrafts' THEN jsonb_build_object('source_app',p_data->'source_app','chat_id',p_data->'chat_id','status',p_data->'status','job_id',p_data->'job_id','draft',p_data->'draft','at',to_char((p_data->>'at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'last_at',CASE WHEN p_data->>'last_at' IS NOT NULL THEN to_char((p_data->>'last_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') END,'creation_time',to_char((p_data->>'creation_time')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'source_deployment',p_data->'source_deployment','source_id',p_data->'source_id')
  ELSE NULL END
 || CASE p_table
  WHEN 'eodReports' THEN jsonb_build_object('submitted_at',to_char((p_data->>'submitted_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))
  WHEN 'checks' THEN jsonb_build_object('source_created_at',to_char((p_data->>'source_created_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))
  WHEN 'decisions' THEN jsonb_build_object('logged_at',to_char((p_data->>'logged_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))
  ELSE '{}'::jsonb END
 || CASE WHEN p_table IN('clientPrefs','hotList','looseDismissed','moneyGoals','projections','renewalPlans','callBriefs','waThreads','replyDrafts')
  THEN jsonb_build_object('source_record',p_data->'source_record','source_deployment',p_data->'source_deployment') ELSE '{}'::jsonb END
 || CASE WHEN p_table IN('clientPrefs','moneyGoals','projections','renewalPlans')
  THEN jsonb_build_object('updated_at',to_char((p_data->>'updated_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))
  WHEN p_table='hotList' THEN jsonb_build_object('created_at',to_char((p_data->>'created_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'updated_at',to_char((p_data->>'updated_at')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))
  ELSE '{}'::jsonb END
$$;
REVOKE ALL ON FUNCTION public.cockpit_native_durable_projection(text,jsonb) FROM PUBLIC,anon,authenticated,service_role;

NOTIFY pgrst,'reload schema';
COMMIT;
