-- Migration: 20260923o_cockpit_domain_tables.sql
-- Phase 3: Target Domain Schemas (Campaigns, Ads, EOD Reports, Decisions, Client Profiles)
-- Idempotent, transaction-wrapped, non-destructive

BEGIN;

-- 1. EOD Reports Table
CREATE TABLE IF NOT EXISTS public.cockpit_eod_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role text NOT NULL,
  day date NOT NULL,
  submitted_at timestamptz,
  energy numeric,
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  computed jsonb NOT NULL DEFAULT '{}'::jsonb,
  slack_ts text,
  source_system text DEFAULT 'convex',
  source_deployment text,
  source_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_cockpit_eod_reports_source UNIQUE (source_deployment, source_id)
);

CREATE INDEX IF NOT EXISTS idx_cockpit_eod_reports_role_day
  ON public.cockpit_eod_reports (role, day DESC);

-- 2. Campaigns Table
CREATE TABLE IF NOT EXISTS public.cockpit_campaigns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid REFERENCES public.clients(id) ON DELETE SET NULL,
  client_name text NOT NULL,
  meta_account_id text,
  meta_campaign_id text,
  task_id text,
  task_url text,
  service_mode text,
  verdict text,
  reason text,
  rank numeric,
  spend_7d numeric DEFAULT 0,
  spend_today numeric DEFAULT 0,
  leads_7d numeric DEFAULT 0,
  leads_today numeric DEFAULT 0,
  cpl numeric,
  frequency numeric,
  link_ctr numeric,
  opt_in_rate numeric,
  synced_at timestamptz,
  raw_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_system text DEFAULT 'convex',
  source_deployment text,
  source_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_cockpit_campaigns_source UNIQUE (source_deployment, source_id)
);

CREATE INDEX IF NOT EXISTS idx_cockpit_campaigns_client
  ON public.cockpit_campaigns (client_name);
CREATE INDEX IF NOT EXISTS idx_cockpit_campaigns_verdict
  ON public.cockpit_campaigns (verdict);

-- 3. Ads Table
CREATE TABLE IF NOT EXISTS public.cockpit_ads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_name text NOT NULL,
  ad_name text NOT NULL,
  meta_ad_id text,
  verdict text,
  reason text,
  spend numeric DEFAULT 0,
  leads numeric DEFAULT 0,
  frequency numeric,
  still_url text,
  thumbnail_url text,
  synced_at timestamptz,
  raw_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_system text DEFAULT 'convex',
  source_deployment text,
  source_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_cockpit_ads_source UNIQUE (source_deployment, source_id)
);

CREATE INDEX IF NOT EXISTS idx_cockpit_ads_campaign
  ON public.cockpit_ads (campaign_name);
CREATE INDEX IF NOT EXISTS idx_cockpit_ads_verdict
  ON public.cockpit_ads (verdict);

-- 4. Decisions Table
CREATE TABLE IF NOT EXISTS public.cockpit_decisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role text NOT NULL,
  day date NOT NULL,
  subject text NOT NULL,
  action text NOT NULL,
  evidence text,
  kind text,
  clickup_task_id text,
  clickup_task_url text,
  metric_at_decision numeric,
  logged_at timestamptz,
  source_system text DEFAULT 'convex',
  source_deployment text,
  source_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_cockpit_decisions_source UNIQUE (source_deployment, source_id)
);

CREATE INDEX IF NOT EXISTS idx_cockpit_decisions_role_day
  ON public.cockpit_decisions (role, day DESC);

-- 5. Client Profiles Table
CREATE TABLE IF NOT EXISTS public.cockpit_client_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name text NOT NULL UNIQUE,
  service text,
  stage text,
  health text,
  kpi jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  overview jsonb NOT NULL DEFAULT '{}'::jsonb,
  provisional jsonb NOT NULL DEFAULT '{}'::jsonb,
  synced_at timestamptz,
  source_system text DEFAULT 'convex',
  source_deployment text,
  source_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cockpit_client_profiles_stage
  ON public.cockpit_client_profiles (stage);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.cockpit_eod_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cockpit_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cockpit_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cockpit_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cockpit_client_profiles ENABLE ROW LEVEL SECURITY;

-- 7. Read Policies (Fail-closed: confirmed Auth users with valid cockpit seat)
DROP POLICY IF EXISTS eod_reports_read_policy ON public.cockpit_eod_reports;
CREATE POLICY eod_reports_read_policy ON public.cockpit_eod_reports
  FOR SELECT TO authenticated
  USING (
    public.cockpit_has_role(role)
    OR public.cockpit_has_role('admin')
    OR public.cockpit_is_ceo()
  );

DROP POLICY IF EXISTS campaigns_read_policy ON public.cockpit_campaigns;
CREATE POLICY campaigns_read_policy ON public.cockpit_campaigns
  FOR SELECT TO authenticated
  USING (
    public.cockpit_has_role('admin')
    OR public.cockpit_is_ceo()
    OR (
      (public.cockpit_has_role('media_buyer') OR public.cockpit_has_role('creative'))
      AND (
        NOT EXISTS (
          SELECT 1 FROM public.cockpit_members cm
          WHERE cm.auth_user_id = auth.uid() AND cm.active AND cm.clients <> '{}'::text[]
        )
        OR client_name = ANY(
          SELECT unnest(cm.clients) FROM public.cockpit_members cm
          WHERE cm.auth_user_id = auth.uid() AND cm.active
        )
      )
    )
  );

DROP POLICY IF EXISTS ads_read_policy ON public.cockpit_ads;
CREATE POLICY ads_read_policy ON public.cockpit_ads
  FOR SELECT TO authenticated
  USING (
    public.cockpit_has_role('admin')
    OR public.cockpit_is_ceo()
    OR public.cockpit_has_role('media_buyer')
    OR public.cockpit_has_role('creative')
    OR public.cockpit_has_role('editor')
  );

DROP POLICY IF EXISTS decisions_read_policy ON public.cockpit_decisions;
CREATE POLICY decisions_read_policy ON public.cockpit_decisions
  FOR SELECT TO authenticated
  USING (
    public.cockpit_has_role(role)
    OR public.cockpit_has_role('admin')
    OR public.cockpit_is_ceo()
  );

DROP POLICY IF EXISTS client_profiles_read_policy ON public.cockpit_client_profiles;
CREATE POLICY client_profiles_read_policy ON public.cockpit_client_profiles
  FOR SELECT TO authenticated
  USING (
    public.cockpit_has_role('admin')
    OR public.cockpit_is_ceo()
    OR (
      (public.cockpit_has_role('csm') OR public.cockpit_has_role('media_buyer'))
      AND (
        NOT EXISTS (
          SELECT 1 FROM public.cockpit_members cm
          WHERE cm.auth_user_id = auth.uid() AND cm.active AND cm.clients <> '{}'::text[]
        )
        OR client_name = ANY(
          SELECT unnest(cm.clients) FROM public.cockpit_members cm
          WHERE cm.auth_user_id = auth.uid() AND cm.active
        )
      )
    )
  );

-- 8. Restrict table privileges:
-- Revoke all direct browser write mutations (INSERT, UPDATE, DELETE)
REVOKE ALL ON TABLE public.cockpit_eod_reports FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.cockpit_campaigns FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.cockpit_ads FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.cockpit_decisions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.cockpit_client_profiles FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.cockpit_eod_reports TO authenticated, service_role;
GRANT SELECT ON TABLE public.cockpit_campaigns TO authenticated, service_role;
GRANT SELECT ON TABLE public.cockpit_ads TO authenticated, service_role;
GRANT SELECT ON TABLE public.cockpit_decisions TO authenticated, service_role;
GRANT SELECT ON TABLE public.cockpit_client_profiles TO authenticated, service_role;

GRANT ALL ON TABLE public.cockpit_eod_reports TO service_role;
GRANT ALL ON TABLE public.cockpit_campaigns TO service_role;
GRANT ALL ON TABLE public.cockpit_ads TO service_role;
GRANT ALL ON TABLE public.cockpit_decisions TO service_role;
GRANT ALL ON TABLE public.cockpit_client_profiles TO service_role;

COMMIT;
